---
deploy:
  -
    provider: script
    script: "bash scripts/goreleaser.sh"
    skip_cleanup: true
    true:
      condition: "$TRAVIS_OS_NAME = linux"
      tags: true
env:
  global:
    - TF_ACC=1
    - GO111MODULE=on
go:
  - 1.16
language: go
script:
  - make
services:
  - docker