/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateUsingPOST4HandlerFunc turns a function with the right signature into a create using p o s t 4 handler
type CreateUsingPOST4HandlerFunc func(CreateUsingPOST4Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateUsingPOST4HandlerFunc) Handle(params CreateUsingPOST4Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateUsingPOST4Handler interface for that can handle valid create using p o s t 4 params
type CreateUsingPOST4Handler interface {
	Handle(CreateUsingPOST4Params, interface{}) middleware.Responder
}

// NewCreateUsingPOST4 creates a new http.Handler for the create using p o s t 4 operation
func NewCreateUsingPOST4(ctx *middleware.Context, handler CreateUsingPOST4Handler) *CreateUsingPOST4 {
	return &CreateUsingPOST4{Context: ctx, Handler: handler}
}

/*CreateUsingPOST4 swagger:route POST /rest/v1/reports Reports createUsingPOST4

Create a new report configuration

*/
type CreateUsingPOST4 struct {
	Context *middleware.Context
	Handler CreateUsingPOST4Handler
}

func (o *CreateUsingPOST4) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateUsingPOST4Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
