/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// DeleteUsingDELETEOKCode is the HTTP code returned for type DeleteUsingDELETEOK
const DeleteUsingDELETEOKCode int = 200

/*DeleteUsingDELETEOK OK

swagger:response deleteUsingDELETEOK
*/
type DeleteUsingDELETEOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeleteUsingDELETEOK creates DeleteUsingDELETEOK with default headers values
func NewDeleteUsingDELETEOK() *DeleteUsingDELETEOK {

	return &DeleteUsingDELETEOK{}
}

// WithPayload adds the payload to the delete using d e l e t e o k response
func (o *DeleteUsingDELETEOK) WithPayload(payload interface{}) *DeleteUsingDELETEOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete using d e l e t e o k response
func (o *DeleteUsingDELETEOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsingDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteUsingDELETENoContentCode is the HTTP code returned for type DeleteUsingDELETENoContent
const DeleteUsingDELETENoContentCode int = 204

/*DeleteUsingDELETENoContent No Content

swagger:response deleteUsingDELETENoContent
*/
type DeleteUsingDELETENoContent struct {
}

// NewDeleteUsingDELETENoContent creates DeleteUsingDELETENoContent with default headers values
func NewDeleteUsingDELETENoContent() *DeleteUsingDELETENoContent {

	return &DeleteUsingDELETENoContent{}
}

// WriteResponse to the client
func (o *DeleteUsingDELETENoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteUsingDELETEBadRequestCode is the HTTP code returned for type DeleteUsingDELETEBadRequest
const DeleteUsingDELETEBadRequestCode int = 400

/*DeleteUsingDELETEBadRequest Bad Request

swagger:response deleteUsingDELETEBadRequest
*/
type DeleteUsingDELETEBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDeleteUsingDELETEBadRequest creates DeleteUsingDELETEBadRequest with default headers values
func NewDeleteUsingDELETEBadRequest() *DeleteUsingDELETEBadRequest {

	return &DeleteUsingDELETEBadRequest{}
}

// WithPayload adds the payload to the delete using d e l e t e bad request response
func (o *DeleteUsingDELETEBadRequest) WithPayload(payload *models.APIErrorFacade) *DeleteUsingDELETEBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete using d e l e t e bad request response
func (o *DeleteUsingDELETEBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsingDELETEBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsingDELETEUnauthorizedCode is the HTTP code returned for type DeleteUsingDELETEUnauthorized
const DeleteUsingDELETEUnauthorizedCode int = 401

/*DeleteUsingDELETEUnauthorized Unauthorized user

swagger:response deleteUsingDELETEUnauthorized
*/
type DeleteUsingDELETEUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDeleteUsingDELETEUnauthorized creates DeleteUsingDELETEUnauthorized with default headers values
func NewDeleteUsingDELETEUnauthorized() *DeleteUsingDELETEUnauthorized {

	return &DeleteUsingDELETEUnauthorized{}
}

// WithPayload adds the payload to the delete using d e l e t e unauthorized response
func (o *DeleteUsingDELETEUnauthorized) WithPayload(payload *models.APIErrorFacade) *DeleteUsingDELETEUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete using d e l e t e unauthorized response
func (o *DeleteUsingDELETEUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsingDELETEUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsingDELETEForbiddenCode is the HTTP code returned for type DeleteUsingDELETEForbidden
const DeleteUsingDELETEForbiddenCode int = 403

/*DeleteUsingDELETEForbidden Forbidden

swagger:response deleteUsingDELETEForbidden
*/
type DeleteUsingDELETEForbidden struct {
}

// NewDeleteUsingDELETEForbidden creates DeleteUsingDELETEForbidden with default headers values
func NewDeleteUsingDELETEForbidden() *DeleteUsingDELETEForbidden {

	return &DeleteUsingDELETEForbidden{}
}

// WriteResponse to the client
func (o *DeleteUsingDELETEForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
