/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetDataUsingGETOKCode is the HTTP code returned for type GetDataUsingGETOK
const GetDataUsingGETOKCode int = 200

/*GetDataUsingGETOK OK

swagger:response getDataUsingGETOK
*/
type GetDataUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReportDataBaseResponse `json:"body,omitempty"`
}

// NewGetDataUsingGETOK creates GetDataUsingGETOK with default headers values
func NewGetDataUsingGETOK() *GetDataUsingGETOK {

	return &GetDataUsingGETOK{}
}

// WithPayload adds the payload to the get data using g e t o k response
func (o *GetDataUsingGETOK) WithPayload(payload *models.ReportDataBaseResponse) *GetDataUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data using g e t o k response
func (o *GetDataUsingGETOK) SetPayload(payload *models.ReportDataBaseResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataUsingGETBadRequestCode is the HTTP code returned for type GetDataUsingGETBadRequest
const GetDataUsingGETBadRequestCode int = 400

/*GetDataUsingGETBadRequest Bad Request

swagger:response getDataUsingGETBadRequest
*/
type GetDataUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetDataUsingGETBadRequest creates GetDataUsingGETBadRequest with default headers values
func NewGetDataUsingGETBadRequest() *GetDataUsingGETBadRequest {

	return &GetDataUsingGETBadRequest{}
}

// WithPayload adds the payload to the get data using g e t bad request response
func (o *GetDataUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *GetDataUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data using g e t bad request response
func (o *GetDataUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataUsingGETUnauthorizedCode is the HTTP code returned for type GetDataUsingGETUnauthorized
const GetDataUsingGETUnauthorizedCode int = 401

/*GetDataUsingGETUnauthorized Unauthorized user

swagger:response getDataUsingGETUnauthorized
*/
type GetDataUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetDataUsingGETUnauthorized creates GetDataUsingGETUnauthorized with default headers values
func NewGetDataUsingGETUnauthorized() *GetDataUsingGETUnauthorized {

	return &GetDataUsingGETUnauthorized{}
}

// WithPayload adds the payload to the get data using g e t unauthorized response
func (o *GetDataUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *GetDataUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data using g e t unauthorized response
func (o *GetDataUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDataUsingGETForbiddenCode is the HTTP code returned for type GetDataUsingGETForbidden
const GetDataUsingGETForbiddenCode int = 403

/*GetDataUsingGETForbidden Forbidden

swagger:response getDataUsingGETForbidden
*/
type GetDataUsingGETForbidden struct {
}

// NewGetDataUsingGETForbidden creates GetDataUsingGETForbidden with default headers values
func NewGetDataUsingGETForbidden() *GetDataUsingGETForbidden {

	return &GetDataUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetDataUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetDataUsingGETNotFoundCode is the HTTP code returned for type GetDataUsingGETNotFound
const GetDataUsingGETNotFoundCode int = 404

/*GetDataUsingGETNotFound Not Found

swagger:response getDataUsingGETNotFound
*/
type GetDataUsingGETNotFound struct {
}

// NewGetDataUsingGETNotFound creates GetDataUsingGETNotFound with default headers values
func NewGetDataUsingGETNotFound() *GetDataUsingGETNotFound {

	return &GetDataUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetDataUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
