/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAllPoliciesUsingGETHandlerFunc turns a function with the right signature into a get all policies using g e t handler
type GetAllPoliciesUsingGETHandlerFunc func(GetAllPoliciesUsingGETParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllPoliciesUsingGETHandlerFunc) Handle(params GetAllPoliciesUsingGETParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllPoliciesUsingGETHandler interface for that can handle valid get all policies using g e t params
type GetAllPoliciesUsingGETHandler interface {
	Handle(GetAllPoliciesUsingGETParams, interface{}) middleware.Responder
}

// NewGetAllPoliciesUsingGET creates a new http.Handler for the get all policies using g e t operation
func NewGetAllPoliciesUsingGET(ctx *middleware.Context, handler GetAllPoliciesUsingGETHandler) *GetAllPoliciesUsingGET {
	return &GetAllPoliciesUsingGET{Context: ctx, Handler: handler}
}

/*GetAllPoliciesUsingGET swagger:route GET /rest/v1/reports/policies Reports getAllPoliciesUsingGET

Get list of all the supported policies

*/
type GetAllPoliciesUsingGET struct {
	Context *middleware.Context
	Handler GetAllPoliciesUsingGETHandler
}

func (o *GetAllPoliciesUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllPoliciesUsingGETParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
