/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetUsingGETParams creates a new GetUsingGETParams object
// no default values defined in spec.
func NewGetUsingGETParams() GetUsingGETParams {

	return GetUsingGETParams{}
}

// GetUsingGETParams contains all the bound params for the get using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters getUsingGET
type GetUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the report ID of a specific report configuration in the user’s scope.
	  Required: true
	  In: path
	*/
	ReportID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUsingGETParams() beforehand.
func (o *GetUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rReportID, rhkReportID, _ := route.Params.GetOK("reportId")
	if err := o.bindReportID(rReportID, rhkReportID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindReportID binds and validates parameter ReportID from path.
func (o *GetUsingGETParams) bindReportID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ReportID = raw

	return nil
}
