/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// ActivateRuleUsingPOSTOKCode is the HTTP code returned for type ActivateRuleUsingPOSTOK
const ActivateRuleUsingPOSTOKCode int = 200

/*ActivateRuleUsingPOSTOK OK

swagger:response activateRuleUsingPOSTOK
*/
type ActivateRuleUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload map[string]string `json:"body,omitempty"`
}

// NewActivateRuleUsingPOSTOK creates ActivateRuleUsingPOSTOK with default headers values
func NewActivateRuleUsingPOSTOK() *ActivateRuleUsingPOSTOK {

	return &ActivateRuleUsingPOSTOK{}
}

// WithPayload adds the payload to the activate rule using p o s t o k response
func (o *ActivateRuleUsingPOSTOK) WithPayload(payload map[string]string) *ActivateRuleUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate rule using p o s t o k response
func (o *ActivateRuleUsingPOSTOK) SetPayload(payload map[string]string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]string, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ActivateRuleUsingPOSTCreatedCode is the HTTP code returned for type ActivateRuleUsingPOSTCreated
const ActivateRuleUsingPOSTCreatedCode int = 201

/*ActivateRuleUsingPOSTCreated Created

swagger:response activateRuleUsingPOSTCreated
*/
type ActivateRuleUsingPOSTCreated struct {
}

// NewActivateRuleUsingPOSTCreated creates ActivateRuleUsingPOSTCreated with default headers values
func NewActivateRuleUsingPOSTCreated() *ActivateRuleUsingPOSTCreated {

	return &ActivateRuleUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ActivateRuleUsingPOSTBadRequestCode is the HTTP code returned for type ActivateRuleUsingPOSTBadRequest
const ActivateRuleUsingPOSTBadRequestCode int = 400

/*ActivateRuleUsingPOSTBadRequest Bad Request

swagger:response activateRuleUsingPOSTBadRequest
*/
type ActivateRuleUsingPOSTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewActivateRuleUsingPOSTBadRequest creates ActivateRuleUsingPOSTBadRequest with default headers values
func NewActivateRuleUsingPOSTBadRequest() *ActivateRuleUsingPOSTBadRequest {

	return &ActivateRuleUsingPOSTBadRequest{}
}

// WithPayload adds the payload to the activate rule using p o s t bad request response
func (o *ActivateRuleUsingPOSTBadRequest) WithPayload(payload *models.APIErrorFacade) *ActivateRuleUsingPOSTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate rule using p o s t bad request response
func (o *ActivateRuleUsingPOSTBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ActivateRuleUsingPOSTUnauthorizedCode is the HTTP code returned for type ActivateRuleUsingPOSTUnauthorized
const ActivateRuleUsingPOSTUnauthorizedCode int = 401

/*ActivateRuleUsingPOSTUnauthorized Unauthorized user

swagger:response activateRuleUsingPOSTUnauthorized
*/
type ActivateRuleUsingPOSTUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewActivateRuleUsingPOSTUnauthorized creates ActivateRuleUsingPOSTUnauthorized with default headers values
func NewActivateRuleUsingPOSTUnauthorized() *ActivateRuleUsingPOSTUnauthorized {

	return &ActivateRuleUsingPOSTUnauthorized{}
}

// WithPayload adds the payload to the activate rule using p o s t unauthorized response
func (o *ActivateRuleUsingPOSTUnauthorized) WithPayload(payload *models.APIErrorFacade) *ActivateRuleUsingPOSTUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate rule using p o s t unauthorized response
func (o *ActivateRuleUsingPOSTUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ActivateRuleUsingPOSTForbiddenCode is the HTTP code returned for type ActivateRuleUsingPOSTForbidden
const ActivateRuleUsingPOSTForbiddenCode int = 403

/*ActivateRuleUsingPOSTForbidden Forbidden

swagger:response activateRuleUsingPOSTForbidden
*/
type ActivateRuleUsingPOSTForbidden struct {
}

// NewActivateRuleUsingPOSTForbidden creates ActivateRuleUsingPOSTForbidden with default headers values
func NewActivateRuleUsingPOSTForbidden() *ActivateRuleUsingPOSTForbidden {

	return &ActivateRuleUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// ActivateRuleUsingPOSTNotFoundCode is the HTTP code returned for type ActivateRuleUsingPOSTNotFound
const ActivateRuleUsingPOSTNotFoundCode int = 404

/*ActivateRuleUsingPOSTNotFound Not Found

swagger:response activateRuleUsingPOSTNotFound
*/
type ActivateRuleUsingPOSTNotFound struct {
}

// NewActivateRuleUsingPOSTNotFound creates ActivateRuleUsingPOSTNotFound with default headers values
func NewActivateRuleUsingPOSTNotFound() *ActivateRuleUsingPOSTNotFound {

	return &ActivateRuleUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *ActivateRuleUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
