/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ActivateRuleUsingPOSTHandlerFunc turns a function with the right signature into a activate rule using p o s t handler
type ActivateRuleUsingPOSTHandlerFunc func(ActivateRuleUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ActivateRuleUsingPOSTHandlerFunc) Handle(params ActivateRuleUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ActivateRuleUsingPOSTHandler interface for that can handle valid activate rule using p o s t params
type ActivateRuleUsingPOSTHandler interface {
	Handle(ActivateRuleUsingPOSTParams, interface{}) middleware.Responder
}

// NewActivateRuleUsingPOST creates a new http.Handler for the activate rule using p o s t operation
func NewActivateRuleUsingPOST(ctx *middleware.Context, handler ActivateRuleUsingPOSTHandler) *ActivateRuleUsingPOST {
	return &ActivateRuleUsingPOST{Context: ctx, Handler: handler}
}

/*ActivateRuleUsingPOST swagger:route POST /rest/v1/rules/enable Response Rules activateRuleUsingPOST

Enable disabled rules

*/
type ActivateRuleUsingPOST struct {
	Context *middleware.Context
	Handler ActivateRuleUsingPOSTHandler
}

func (o *ActivateRuleUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewActivateRuleUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
