/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateRuleUsingPOSTHandlerFunc turns a function with the right signature into a create rule using p o s t handler
type CreateRuleUsingPOSTHandlerFunc func(CreateRuleUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRuleUsingPOSTHandlerFunc) Handle(params CreateRuleUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateRuleUsingPOSTHandler interface for that can handle valid create rule using p o s t params
type CreateRuleUsingPOSTHandler interface {
	Handle(CreateRuleUsingPOSTParams, interface{}) middleware.Responder
}

// NewCreateRuleUsingPOST creates a new http.Handler for the create rule using p o s t operation
func NewCreateRuleUsingPOST(ctx *middleware.Context, handler CreateRuleUsingPOSTHandler) *CreateRuleUsingPOST {
	return &CreateRuleUsingPOST{Context: ctx, Handler: handler}
}

/*CreateRuleUsingPOST swagger:route POST /rest/v1/rules Response Rules createRuleUsingPOST

Create a new rule

*/
type CreateRuleUsingPOST struct {
	Context *middleware.Context
	Handler CreateRuleUsingPOSTHandler
}

func (o *CreateRuleUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRuleUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
