/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// DisableRuleUsingPOSTOKCode is the HTTP code returned for type DisableRuleUsingPOSTOK
const DisableRuleUsingPOSTOKCode int = 200

/*DisableRuleUsingPOSTOK OK

swagger:response disableRuleUsingPOSTOK
*/
type DisableRuleUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload map[string]string `json:"body,omitempty"`
}

// NewDisableRuleUsingPOSTOK creates DisableRuleUsingPOSTOK with default headers values
func NewDisableRuleUsingPOSTOK() *DisableRuleUsingPOSTOK {

	return &DisableRuleUsingPOSTOK{}
}

// WithPayload adds the payload to the disable rule using p o s t o k response
func (o *DisableRuleUsingPOSTOK) WithPayload(payload map[string]string) *DisableRuleUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the disable rule using p o s t o k response
func (o *DisableRuleUsingPOSTOK) SetPayload(payload map[string]string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]string, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DisableRuleUsingPOSTCreatedCode is the HTTP code returned for type DisableRuleUsingPOSTCreated
const DisableRuleUsingPOSTCreatedCode int = 201

/*DisableRuleUsingPOSTCreated Created

swagger:response disableRuleUsingPOSTCreated
*/
type DisableRuleUsingPOSTCreated struct {
}

// NewDisableRuleUsingPOSTCreated creates DisableRuleUsingPOSTCreated with default headers values
func NewDisableRuleUsingPOSTCreated() *DisableRuleUsingPOSTCreated {

	return &DisableRuleUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// DisableRuleUsingPOSTBadRequestCode is the HTTP code returned for type DisableRuleUsingPOSTBadRequest
const DisableRuleUsingPOSTBadRequestCode int = 400

/*DisableRuleUsingPOSTBadRequest Bad Request

swagger:response disableRuleUsingPOSTBadRequest
*/
type DisableRuleUsingPOSTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDisableRuleUsingPOSTBadRequest creates DisableRuleUsingPOSTBadRequest with default headers values
func NewDisableRuleUsingPOSTBadRequest() *DisableRuleUsingPOSTBadRequest {

	return &DisableRuleUsingPOSTBadRequest{}
}

// WithPayload adds the payload to the disable rule using p o s t bad request response
func (o *DisableRuleUsingPOSTBadRequest) WithPayload(payload *models.APIErrorFacade) *DisableRuleUsingPOSTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the disable rule using p o s t bad request response
func (o *DisableRuleUsingPOSTBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DisableRuleUsingPOSTUnauthorizedCode is the HTTP code returned for type DisableRuleUsingPOSTUnauthorized
const DisableRuleUsingPOSTUnauthorizedCode int = 401

/*DisableRuleUsingPOSTUnauthorized Unauthorized user

swagger:response disableRuleUsingPOSTUnauthorized
*/
type DisableRuleUsingPOSTUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDisableRuleUsingPOSTUnauthorized creates DisableRuleUsingPOSTUnauthorized with default headers values
func NewDisableRuleUsingPOSTUnauthorized() *DisableRuleUsingPOSTUnauthorized {

	return &DisableRuleUsingPOSTUnauthorized{}
}

// WithPayload adds the payload to the disable rule using p o s t unauthorized response
func (o *DisableRuleUsingPOSTUnauthorized) WithPayload(payload *models.APIErrorFacade) *DisableRuleUsingPOSTUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the disable rule using p o s t unauthorized response
func (o *DisableRuleUsingPOSTUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DisableRuleUsingPOSTForbiddenCode is the HTTP code returned for type DisableRuleUsingPOSTForbidden
const DisableRuleUsingPOSTForbiddenCode int = 403

/*DisableRuleUsingPOSTForbidden Forbidden

swagger:response disableRuleUsingPOSTForbidden
*/
type DisableRuleUsingPOSTForbidden struct {
}

// NewDisableRuleUsingPOSTForbidden creates DisableRuleUsingPOSTForbidden with default headers values
func NewDisableRuleUsingPOSTForbidden() *DisableRuleUsingPOSTForbidden {

	return &DisableRuleUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DisableRuleUsingPOSTNotFoundCode is the HTTP code returned for type DisableRuleUsingPOSTNotFound
const DisableRuleUsingPOSTNotFoundCode int = 404

/*DisableRuleUsingPOSTNotFound Not Found

swagger:response disableRuleUsingPOSTNotFound
*/
type DisableRuleUsingPOSTNotFound struct {
}

// NewDisableRuleUsingPOSTNotFound creates DisableRuleUsingPOSTNotFound with default headers values
func NewDisableRuleUsingPOSTNotFound() *DisableRuleUsingPOSTNotFound {

	return &DisableRuleUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *DisableRuleUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
