/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetAllRulesByFilterUsingGETURL generates an URL for the get all rules by filter using g e t operation
type GetAllRulesByFilterUsingGETURL struct {
	CloudType string
	Filter    *string
	PageNo    int32
	PageSize  int32
	RuleType  string
	SortField *string
	SortOrder *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAllRulesByFilterUsingGETURL) WithBasePath(bp string) *GetAllRulesByFilterUsingGETURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAllRulesByFilterUsingGETURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetAllRulesByFilterUsingGETURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/rest/v1/rules"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/cloudview-api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	cloudTypeQ := o.CloudType
	if cloudTypeQ != "" {
		qs.Set("cloudType", cloudTypeQ)
	}

	var filterQ string
	if o.Filter != nil {
		filterQ = *o.Filter
	}
	if filterQ != "" {
		qs.Set("filter", filterQ)
	}

	pageNoQ := swag.FormatInt32(o.PageNo)
	if pageNoQ != "" {
		qs.Set("pageNo", pageNoQ)
	}

	pageSizeQ := swag.FormatInt32(o.PageSize)
	if pageSizeQ != "" {
		qs.Set("pageSize", pageSizeQ)
	}

	ruleTypeQ := o.RuleType
	if ruleTypeQ != "" {
		qs.Set("ruleType", ruleTypeQ)
	}

	var sortFieldQ string
	if o.SortField != nil {
		sortFieldQ = *o.SortField
	}
	if sortFieldQ != "" {
		qs.Set("sortField", sortFieldQ)
	}

	var sortOrderQ string
	if o.SortOrder != nil {
		sortOrderQ = *o.SortOrder
	}
	if sortOrderQ != "" {
		qs.Set("sortOrder", sortOrderQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetAllRulesByFilterUsingGETURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetAllRulesByFilterUsingGETURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetAllRulesByFilterUsingGETURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetAllRulesByFilterUsingGETURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetAllRulesByFilterUsingGETURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetAllRulesByFilterUsingGETURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
