/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateUsingPOSTHandlerFunc turns a function with the right signature into a create using p o s t handler
type CreateUsingPOSTHandlerFunc func(CreateUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateUsingPOSTHandlerFunc) Handle(params CreateUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateUsingPOSTHandler interface for that can handle valid create using p o s t params
type CreateUsingPOSTHandler interface {
	Handle(CreateUsingPOSTParams, interface{}) middleware.Responder
}

// NewCreateUsingPOST creates a new http.Handler for the create using p o s t operation
func NewCreateUsingPOST(ctx *middleware.Context, handler CreateUsingPOSTHandler) *CreateUsingPOST {
	return &CreateUsingPOST{Context: ctx, Handler: handler}
}

/*CreateUsingPOST swagger:route POST /rest/v1/azure/connectors Azure Connector createUsingPOST

Create a new connector

*/
type CreateUsingPOST struct {
	Context *middleware.Context
	Handler CreateUsingPOSTHandler
}

func (o *CreateUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
