/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConnectorsUsingDELETEHandlerFunc turns a function with the right signature into a delete connectors using d e l e t e handler
type DeleteConnectorsUsingDELETEHandlerFunc func(DeleteConnectorsUsingDELETEParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConnectorsUsingDELETEHandlerFunc) Handle(params DeleteConnectorsUsingDELETEParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteConnectorsUsingDELETEHandler interface for that can handle valid delete connectors using d e l e t e params
type DeleteConnectorsUsingDELETEHandler interface {
	Handle(DeleteConnectorsUsingDELETEParams, interface{}) middleware.Responder
}

// NewDeleteConnectorsUsingDELETE creates a new http.Handler for the delete connectors using d e l e t e operation
func NewDeleteConnectorsUsingDELETE(ctx *middleware.Context, handler DeleteConnectorsUsingDELETEHandler) *DeleteConnectorsUsingDELETE {
	return &DeleteConnectorsUsingDELETE{Context: ctx, Handler: handler}
}

/*DeleteConnectorsUsingDELETE swagger:route DELETE /rest/v1/azure/connectors Azure Connector deleteConnectorsUsingDELETE

Delete the provided connectors

*/
type DeleteConnectorsUsingDELETE struct {
	Context *middleware.Context
	Handler DeleteConnectorsUsingDELETEHandler
}

func (o *DeleteConnectorsUsingDELETE) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteConnectorsUsingDELETEParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
