/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetListUsingGETOKCode is the HTTP code returned for type GetListUsingGETOK
const GetListUsingGETOKCode int = 200

/*GetListUsingGETOK OK

swagger:response getListUsingGETOK
*/
type GetListUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.PageImplAzureConnectorResponse `json:"body,omitempty"`
}

// NewGetListUsingGETOK creates GetListUsingGETOK with default headers values
func NewGetListUsingGETOK() *GetListUsingGETOK {

	return &GetListUsingGETOK{}
}

// WithPayload adds the payload to the get list using g e t o k response
func (o *GetListUsingGETOK) WithPayload(payload *models.PageImplAzureConnectorResponse) *GetListUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t o k response
func (o *GetListUsingGETOK) SetPayload(payload *models.PageImplAzureConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGETBadRequestCode is the HTTP code returned for type GetListUsingGETBadRequest
const GetListUsingGETBadRequestCode int = 400

/*GetListUsingGETBadRequest Bad Request

swagger:response getListUsingGETBadRequest
*/
type GetListUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetListUsingGETBadRequest creates GetListUsingGETBadRequest with default headers values
func NewGetListUsingGETBadRequest() *GetListUsingGETBadRequest {

	return &GetListUsingGETBadRequest{}
}

// WithPayload adds the payload to the get list using g e t bad request response
func (o *GetListUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *GetListUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t bad request response
func (o *GetListUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGETUnauthorizedCode is the HTTP code returned for type GetListUsingGETUnauthorized
const GetListUsingGETUnauthorizedCode int = 401

/*GetListUsingGETUnauthorized Unauthorized user

swagger:response getListUsingGETUnauthorized
*/
type GetListUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetListUsingGETUnauthorized creates GetListUsingGETUnauthorized with default headers values
func NewGetListUsingGETUnauthorized() *GetListUsingGETUnauthorized {

	return &GetListUsingGETUnauthorized{}
}

// WithPayload adds the payload to the get list using g e t unauthorized response
func (o *GetListUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *GetListUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t unauthorized response
func (o *GetListUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGETForbiddenCode is the HTTP code returned for type GetListUsingGETForbidden
const GetListUsingGETForbiddenCode int = 403

/*GetListUsingGETForbidden Forbidden

swagger:response getListUsingGETForbidden
*/
type GetListUsingGETForbidden struct {
}

// NewGetListUsingGETForbidden creates GetListUsingGETForbidden with default headers values
func NewGetListUsingGETForbidden() *GetListUsingGETForbidden {

	return &GetListUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetListUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetListUsingGETNotFoundCode is the HTTP code returned for type GetListUsingGETNotFound
const GetListUsingGETNotFoundCode int = 404

/*GetListUsingGETNotFound Not Found

swagger:response getListUsingGETNotFound
*/
type GetListUsingGETNotFound struct {
}

// NewGetListUsingGETNotFound creates GetListUsingGETNotFound with default headers values
func NewGetListUsingGETNotFound() *GetListUsingGETNotFound {

	return &GetListUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetListUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
