/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewRunConnectorUsingPOSTParams creates a new RunConnectorUsingPOSTParams object
// no default values defined in spec.
func NewRunConnectorUsingPOSTParams() RunConnectorUsingPOSTParams {

	return RunConnectorUsingPOSTParams{}
}

// RunConnectorUsingPOSTParams contains all the bound params for the run connector using p o s t operation
// typically these are obtained from a http.Request
//
// swagger:parameters runConnectorUsingPOST
type RunConnectorUsingPOSTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the IDs of the connectors that you want to execute/run.
	  Required: true
	  In: body
	*/
	ConnectorIds []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRunConnectorUsingPOSTParams() beforehand.
func (o *RunConnectorUsingPOSTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("connectorIds", "body", ""))
			} else {
				res = append(res, errors.NewParseError("connectorIds", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.ConnectorIds = body
		}
	} else {
		res = append(res, errors.Required("connectorIds", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
