/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RunConnectorUsingPOSTHandlerFunc turns a function with the right signature into a run connector using p o s t handler
type RunConnectorUsingPOSTHandlerFunc func(RunConnectorUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RunConnectorUsingPOSTHandlerFunc) Handle(params RunConnectorUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RunConnectorUsingPOSTHandler interface for that can handle valid run connector using p o s t params
type RunConnectorUsingPOSTHandler interface {
	Handle(RunConnectorUsingPOSTParams, interface{}) middleware.Responder
}

// NewRunConnectorUsingPOST creates a new http.Handler for the run connector using p o s t operation
func NewRunConnectorUsingPOST(ctx *middleware.Context, handler RunConnectorUsingPOSTHandler) *RunConnectorUsingPOST {
	return &RunConnectorUsingPOST{Context: ctx, Handler: handler}
}

/*RunConnectorUsingPOST swagger:route POST /rest/v1/azure/connectors/run Azure Connector runConnectorUsingPOST

Run the provided connectors

*/
type RunConnectorUsingPOST struct {
	Context *middleware.Context
	Handler RunConnectorUsingPOSTHandler
}

func (o *RunConnectorUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRunConnectorUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
