/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// RunConnectorUsingPOSTOKCode is the HTTP code returned for type RunConnectorUsingPOSTOK
const RunConnectorUsingPOSTOKCode int = 200

/*RunConnectorUsingPOSTOK OK

swagger:response runConnectorUsingPOSTOK
*/
type RunConnectorUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewRunConnectorUsingPOSTOK creates RunConnectorUsingPOSTOK with default headers values
func NewRunConnectorUsingPOSTOK() *RunConnectorUsingPOSTOK {

	return &RunConnectorUsingPOSTOK{}
}

// WithPayload adds the payload to the run connector using p o s t o k response
func (o *RunConnectorUsingPOSTOK) WithPayload(payload interface{}) *RunConnectorUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the run connector using p o s t o k response
func (o *RunConnectorUsingPOSTOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RunConnectorUsingPOSTCreatedCode is the HTTP code returned for type RunConnectorUsingPOSTCreated
const RunConnectorUsingPOSTCreatedCode int = 201

/*RunConnectorUsingPOSTCreated Created

swagger:response runConnectorUsingPOSTCreated
*/
type RunConnectorUsingPOSTCreated struct {
}

// NewRunConnectorUsingPOSTCreated creates RunConnectorUsingPOSTCreated with default headers values
func NewRunConnectorUsingPOSTCreated() *RunConnectorUsingPOSTCreated {

	return &RunConnectorUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// RunConnectorUsingPOSTBadRequestCode is the HTTP code returned for type RunConnectorUsingPOSTBadRequest
const RunConnectorUsingPOSTBadRequestCode int = 400

/*RunConnectorUsingPOSTBadRequest Bad Request

swagger:response runConnectorUsingPOSTBadRequest
*/
type RunConnectorUsingPOSTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewRunConnectorUsingPOSTBadRequest creates RunConnectorUsingPOSTBadRequest with default headers values
func NewRunConnectorUsingPOSTBadRequest() *RunConnectorUsingPOSTBadRequest {

	return &RunConnectorUsingPOSTBadRequest{}
}

// WithPayload adds the payload to the run connector using p o s t bad request response
func (o *RunConnectorUsingPOSTBadRequest) WithPayload(payload *models.APIErrorFacade) *RunConnectorUsingPOSTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the run connector using p o s t bad request response
func (o *RunConnectorUsingPOSTBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RunConnectorUsingPOSTUnauthorizedCode is the HTTP code returned for type RunConnectorUsingPOSTUnauthorized
const RunConnectorUsingPOSTUnauthorizedCode int = 401

/*RunConnectorUsingPOSTUnauthorized Unauthorized user

swagger:response runConnectorUsingPOSTUnauthorized
*/
type RunConnectorUsingPOSTUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewRunConnectorUsingPOSTUnauthorized creates RunConnectorUsingPOSTUnauthorized with default headers values
func NewRunConnectorUsingPOSTUnauthorized() *RunConnectorUsingPOSTUnauthorized {

	return &RunConnectorUsingPOSTUnauthorized{}
}

// WithPayload adds the payload to the run connector using p o s t unauthorized response
func (o *RunConnectorUsingPOSTUnauthorized) WithPayload(payload *models.APIErrorFacade) *RunConnectorUsingPOSTUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the run connector using p o s t unauthorized response
func (o *RunConnectorUsingPOSTUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RunConnectorUsingPOSTForbiddenCode is the HTTP code returned for type RunConnectorUsingPOSTForbidden
const RunConnectorUsingPOSTForbiddenCode int = 403

/*RunConnectorUsingPOSTForbidden Forbidden

swagger:response runConnectorUsingPOSTForbidden
*/
type RunConnectorUsingPOSTForbidden struct {
}

// NewRunConnectorUsingPOSTForbidden creates RunConnectorUsingPOSTForbidden with default headers values
func NewRunConnectorUsingPOSTForbidden() *RunConnectorUsingPOSTForbidden {

	return &RunConnectorUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RunConnectorUsingPOSTNotFoundCode is the HTTP code returned for type RunConnectorUsingPOSTNotFound
const RunConnectorUsingPOSTNotFoundCode int = 404

/*RunConnectorUsingPOSTNotFound Not Found

swagger:response runConnectorUsingPOSTNotFound
*/
type RunConnectorUsingPOSTNotFound struct {
}

// NewRunConnectorUsingPOSTNotFound creates RunConnectorUsingPOSTNotFound with default headers values
func NewRunConnectorUsingPOSTNotFound() *RunConnectorUsingPOSTNotFound {

	return &RunConnectorUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *RunConnectorUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
