/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateConnectorUsingPUTHandlerFunc turns a function with the right signature into a update connector using p u t handler
type UpdateConnectorUsingPUTHandlerFunc func(UpdateConnectorUsingPUTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConnectorUsingPUTHandlerFunc) Handle(params UpdateConnectorUsingPUTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateConnectorUsingPUTHandler interface for that can handle valid update connector using p u t params
type UpdateConnectorUsingPUTHandler interface {
	Handle(UpdateConnectorUsingPUTParams, interface{}) middleware.Responder
}

// NewUpdateConnectorUsingPUT creates a new http.Handler for the update connector using p u t operation
func NewUpdateConnectorUsingPUT(ctx *middleware.Context, handler UpdateConnectorUsingPUTHandler) *UpdateConnectorUsingPUT {
	return &UpdateConnectorUsingPUT{Context: ctx, Handler: handler}
}

/*UpdateConnectorUsingPUT swagger:route PUT /rest/v1/azure/connectors/{connectorId} Azure Connector updateConnectorUsingPUT

Update the existing connector

*/
type UpdateConnectorUsingPUT struct {
	Context *middleware.Context
	Handler UpdateConnectorUsingPUTHandler
}

func (o *UpdateConnectorUsingPUT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateConnectorUsingPUTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
