/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetEvaluatedResourcesUsingGETOKCode is the HTTP code returned for type GetEvaluatedResourcesUsingGETOK
const GetEvaluatedResourcesUsingGETOKCode int = 200

/*GetEvaluatedResourcesUsingGETOK OK

swagger:response getEvaluatedResourcesUsingGETOK
*/
type GetEvaluatedResourcesUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.PageImplAwsEvaluationDetailResponse `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGETOK creates GetEvaluatedResourcesUsingGETOK with default headers values
func NewGetEvaluatedResourcesUsingGETOK() *GetEvaluatedResourcesUsingGETOK {

	return &GetEvaluatedResourcesUsingGETOK{}
}

// WithPayload adds the payload to the get evaluated resources using g e t o k response
func (o *GetEvaluatedResourcesUsingGETOK) WithPayload(payload *models.PageImplAwsEvaluationDetailResponse) *GetEvaluatedResourcesUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t o k response
func (o *GetEvaluatedResourcesUsingGETOK) SetPayload(payload *models.PageImplAwsEvaluationDetailResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGETBadRequestCode is the HTTP code returned for type GetEvaluatedResourcesUsingGETBadRequest
const GetEvaluatedResourcesUsingGETBadRequestCode int = 400

/*GetEvaluatedResourcesUsingGETBadRequest Bad Request

swagger:response getEvaluatedResourcesUsingGETBadRequest
*/
type GetEvaluatedResourcesUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGETBadRequest creates GetEvaluatedResourcesUsingGETBadRequest with default headers values
func NewGetEvaluatedResourcesUsingGETBadRequest() *GetEvaluatedResourcesUsingGETBadRequest {

	return &GetEvaluatedResourcesUsingGETBadRequest{}
}

// WithPayload adds the payload to the get evaluated resources using g e t bad request response
func (o *GetEvaluatedResourcesUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *GetEvaluatedResourcesUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t bad request response
func (o *GetEvaluatedResourcesUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGETUnauthorizedCode is the HTTP code returned for type GetEvaluatedResourcesUsingGETUnauthorized
const GetEvaluatedResourcesUsingGETUnauthorizedCode int = 401

/*GetEvaluatedResourcesUsingGETUnauthorized Unauthorized user

swagger:response getEvaluatedResourcesUsingGETUnauthorized
*/
type GetEvaluatedResourcesUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGETUnauthorized creates GetEvaluatedResourcesUsingGETUnauthorized with default headers values
func NewGetEvaluatedResourcesUsingGETUnauthorized() *GetEvaluatedResourcesUsingGETUnauthorized {

	return &GetEvaluatedResourcesUsingGETUnauthorized{}
}

// WithPayload adds the payload to the get evaluated resources using g e t unauthorized response
func (o *GetEvaluatedResourcesUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *GetEvaluatedResourcesUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t unauthorized response
func (o *GetEvaluatedResourcesUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGETForbiddenCode is the HTTP code returned for type GetEvaluatedResourcesUsingGETForbidden
const GetEvaluatedResourcesUsingGETForbiddenCode int = 403

/*GetEvaluatedResourcesUsingGETForbidden Forbidden

swagger:response getEvaluatedResourcesUsingGETForbidden
*/
type GetEvaluatedResourcesUsingGETForbidden struct {
}

// NewGetEvaluatedResourcesUsingGETForbidden creates GetEvaluatedResourcesUsingGETForbidden with default headers values
func NewGetEvaluatedResourcesUsingGETForbidden() *GetEvaluatedResourcesUsingGETForbidden {

	return &GetEvaluatedResourcesUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetEvaluatedResourcesUsingGETNotFoundCode is the HTTP code returned for type GetEvaluatedResourcesUsingGETNotFound
const GetEvaluatedResourcesUsingGETNotFoundCode int = 404

/*GetEvaluatedResourcesUsingGETNotFound Not Found

swagger:response getEvaluatedResourcesUsingGETNotFound
*/
type GetEvaluatedResourcesUsingGETNotFound struct {
}

// NewGetEvaluatedResourcesUsingGETNotFound creates GetEvaluatedResourcesUsingGETNotFound with default headers values
func NewGetEvaluatedResourcesUsingGETNotFound() *GetEvaluatedResourcesUsingGETNotFound {

	return &GetEvaluatedResourcesUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
