/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetEvaluatedControlsUsingGETURL generates an URL for the get evaluated controls using g e t operation
type GetEvaluatedControlsUsingGETURL struct {
	AccountID string

	Filter   *string
	PageNo   *int32
	PageSize *int32

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetEvaluatedControlsUsingGETURL) WithBasePath(bp string) *GetEvaluatedControlsUsingGETURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetEvaluatedControlsUsingGETURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetEvaluatedControlsUsingGETURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/rest/v1/aws/evaluations/{accountId}"

	accountID := o.AccountID
	if accountID != "" {
		_path = strings.Replace(_path, "{accountId}", accountID, -1)
	} else {
		return nil, errors.New("accountId is required on GetEvaluatedControlsUsingGETURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/cloudview-api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var filterQ string
	if o.Filter != nil {
		filterQ = *o.Filter
	}
	if filterQ != "" {
		qs.Set("filter", filterQ)
	}

	var pageNoQ string
	if o.PageNo != nil {
		pageNoQ = swag.FormatInt32(*o.PageNo)
	}
	if pageNoQ != "" {
		qs.Set("pageNo", pageNoQ)
	}

	var pageSizeQ string
	if o.PageSize != nil {
		pageSizeQ = swag.FormatInt32(*o.PageSize)
	}
	if pageSizeQ != "" {
		qs.Set("pageSize", pageSizeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetEvaluatedControlsUsingGETURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetEvaluatedControlsUsingGETURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetEvaluatedControlsUsingGETURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetEvaluatedControlsUsingGETURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetEvaluatedControlsUsingGETURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetEvaluatedControlsUsingGETURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
