/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package assessment_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateReportUsingPOSTHandlerFunc turns a function with the right signature into a create report using p o s t handler
type CreateReportUsingPOSTHandlerFunc func(CreateReportUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateReportUsingPOSTHandlerFunc) Handle(params CreateReportUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateReportUsingPOSTHandler interface for that can handle valid create report using p o s t params
type CreateReportUsingPOSTHandler interface {
	Handle(CreateReportUsingPOSTParams, interface{}) middleware.Responder
}

// NewCreateReportUsingPOST creates a new http.Handler for the create report using p o s t operation
func NewCreateReportUsingPOST(ctx *middleware.Context, handler CreateReportUsingPOSTHandler) *CreateReportUsingPOST {
	return &CreateReportUsingPOST{Context: ctx, Handler: handler}
}

/*CreateReportUsingPOST swagger:route POST /rest/v1/report/assessment/create Assessment Reports createReportUsingPOST

API to create new  Assessment report

*/
type CreateReportUsingPOST struct {
	Context *middleware.Context
	Handler CreateReportUsingPOSTHandler
}

func (o *CreateReportUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateReportUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
