/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package assessment_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DownloadReportUsingGETHandlerFunc turns a function with the right signature into a download report using g e t handler
type DownloadReportUsingGETHandlerFunc func(DownloadReportUsingGETParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DownloadReportUsingGETHandlerFunc) Handle(params DownloadReportUsingGETParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DownloadReportUsingGETHandler interface for that can handle valid download report using g e t params
type DownloadReportUsingGETHandler interface {
	Handle(DownloadReportUsingGETParams, interface{}) middleware.Responder
}

// NewDownloadReportUsingGET creates a new http.Handler for the download report using g e t operation
func NewDownloadReportUsingGET(ctx *middleware.Context, handler DownloadReportUsingGETHandler) *DownloadReportUsingGET {
	return &DownloadReportUsingGET{Context: ctx, Handler: handler}
}

/*DownloadReportUsingGET swagger:route GET /rest/v1/report/assessment/{reportId}/download Assessment Reports downloadReportUsingGET

API to download report

*/
type DownloadReportUsingGET struct {
	Context *middleware.Context
	Handler DownloadReportUsingGETHandler
}

func (o *DownloadReportUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDownloadReportUsingGETParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
