/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package assessment_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RerunReportUsingPOSTHandlerFunc turns a function with the right signature into a rerun report using p o s t handler
type RerunReportUsingPOSTHandlerFunc func(RerunReportUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RerunReportUsingPOSTHandlerFunc) Handle(params RerunReportUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RerunReportUsingPOSTHandler interface for that can handle valid rerun report using p o s t params
type RerunReportUsingPOSTHandler interface {
	Handle(RerunReportUsingPOSTParams, interface{}) middleware.Responder
}

// NewRerunReportUsingPOST creates a new http.Handler for the rerun report using p o s t operation
func NewRerunReportUsingPOST(ctx *middleware.Context, handler RerunReportUsingPOSTHandler) *RerunReportUsingPOST {
	return &RerunReportUsingPOST{Context: ctx, Handler: handler}
}

/*RerunReportUsingPOST swagger:route POST /rest/v1/report/assessment/{reportId}/rerun Assessment Reports rerunReportUsingPOST

API to Re-Run report

*/
type RerunReportUsingPOST struct {
	Context *middleware.Context
	Handler RerunReportUsingPOSTHandler
}

func (o *RerunReportUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRerunReportUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
