// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AzureConnectorUpdateRequest AzureConnectorUpdateRequest
//
// swagger:model AzureConnectorUpdateRequest
type AzureConnectorUpdateRequest struct {

	// application Id
	ApplicationID string `json:"applicationId,omitempty"`

	// authentication key
	AuthenticationKey string `json:"authenticationKey,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// directory Id
	DirectoryID string `json:"directoryId,omitempty"`

	// is gov cloud
	IsGovCloud bool `json:"isGovCloud,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// polling frequency
	PollingFrequency *RunFrequency `json:"pollingFrequency,omitempty"`

	// remediation enabled
	RemediationEnabled bool `json:"remediationEnabled,omitempty"`
}

// Validate validates this azure connector update request
func (m *AzureConnectorUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePollingFrequency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AzureConnectorUpdateRequest) validatePollingFrequency(formats strfmt.Registry) error {

	if swag.IsZero(m.PollingFrequency) { // not required
		return nil
	}

	if m.PollingFrequency != nil {
		if err := m.PollingFrequency.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pollingFrequency")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AzureConnectorUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureConnectorUpdateRequest) UnmarshalBinary(b []byte) error {
	var res AzureConnectorUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
