// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectorGroupModifyRequest ConnectorGroupModifyRequest
//
// swagger:model ConnectorGroupModifyRequest
type ConnectorGroupModifyRequest struct {

	// account identifiers
	AccountIdentifiers []string `json:"accountIdentifiers"`

	// add
	Add *ModifyRequest `json:"add,omitempty"`

	// remove
	Remove *ModifyRequest `json:"remove,omitempty"`
}

// Validate validates this connector group modify request
func (m *ConnectorGroupModifyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemove(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConnectorGroupModifyRequest) validateAdd(formats strfmt.Registry) error {

	if swag.IsZero(m.Add) { // not required
		return nil
	}

	if m.Add != nil {
		if err := m.Add.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("add")
			}
			return err
		}
	}

	return nil
}

func (m *ConnectorGroupModifyRequest) validateRemove(formats strfmt.Registry) error {

	if swag.IsZero(m.Remove) { // not required
		return nil
	}

	if m.Remove != nil {
		if err := m.Remove.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("remove")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConnectorGroupModifyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectorGroupModifyRequest) UnmarshalBinary(b []byte) error {
	var res ConnectorGroupModifyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
