// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Connector Connector
//
// swagger:model Connector
type Connector struct {

	// account identifier
	AccountIdentifier string `json:"accountIdentifier,omitempty"`

	// cloud type
	CloudType string `json:"cloudType,omitempty"`

	// connector Uuid
	ConnectorUUID string `json:"connectorUuid,omitempty"`
}

// Validate validates this connector
func (m *Connector) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Connector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Connector) UnmarshalBinary(b []byte) error {
	var res Connector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
