// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateGroupResponse CreateGroupResponse
//
// swagger:model CreateGroupResponse
type CreateGroupResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// group Id
	GroupID string `json:"groupId,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this create group response
func (m *CreateGroupResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateGroupResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateGroupResponse) UnmarshalBinary(b []byte) error {
	var res CreateGroupResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
