// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataStats DataStats
//
// swagger:model DataStats
type DataStats struct {

	// fail count
	FailCount int64 `json:"failCount,omitempty"`

	// fail percent
	FailPercent float64 `json:"failPercent,omitempty"`

	// pass count
	PassCount int64 `json:"passCount,omitempty"`

	// pass percent
	PassPercent float64 `json:"passPercent,omitempty"`
}

// Validate validates this data stats
func (m *DataStats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataStats) UnmarshalBinary(b []byte) error {
	var res DataStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
