// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EmailActionUpdateRequest EmailActionUpdateRequest
//
// swagger:model EmailActionUpdateRequest
type EmailActionUpdateRequest struct {

	// action description
	ActionDescription string `json:"actionDescription,omitempty"`

	// action name
	ActionName string `json:"actionName,omitempty"`

	// recipients
	Recipients []string `json:"recipients"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this email action update request
func (m *EmailActionUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EmailActionUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmailActionUpdateRequest) UnmarshalBinary(b []byte) error {
	var res EmailActionUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
