// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExceptionListResponse ExceptionListResponse
//
// swagger:model ExceptionListResponse
type ExceptionListResponse struct {

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// created by Uuid
	// Format: uuid
	CreatedByUUID strfmt.UUID `json:"createdByUuid,omitempty"`

	// created on
	CreatedOn string `json:"createdOn,omitempty"`

	// customer Id
	CustomerID int64 `json:"customerId,omitempty"`

	// customer Uuid
	// Format: uuid
	CustomerUUID strfmt.UUID `json:"customerUuid,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// ending date
	EndingDate string `json:"endingDate,omitempty"`

	// information security policy
	InformationSecurityPolicy string `json:"informationSecurityPolicy,omitempty"`

	// information security procedure
	InformationSecurityProcedure string `json:"informationSecurityProcedure,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// reference doc link
	ReferenceDocLink string `json:"referenceDocLink,omitempty"`

	// starting date
	StartingDate string `json:"startingDate,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// updated by
	UpdatedBy string `json:"updatedBy,omitempty"`

	// updated by Uuid
	// Format: uuid
	UpdatedByUUID strfmt.UUID `json:"updatedByUuid,omitempty"`

	// updated on
	UpdatedOn string `json:"updatedOn,omitempty"`

	// uuid
	// Format: uuid
	UUID strfmt.UUID `json:"uuid,omitempty"`
}

// Validate validates this exception list response
func (m *ExceptionListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedByUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomerUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedByUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExceptionListResponse) validateCreatedByUUID(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedByUUID) { // not required
		return nil
	}

	if err := validate.FormatOf("createdByUuid", "body", "uuid", m.CreatedByUUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ExceptionListResponse) validateCustomerUUID(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomerUUID) { // not required
		return nil
	}

	if err := validate.FormatOf("customerUuid", "body", "uuid", m.CustomerUUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ExceptionListResponse) validateUpdatedByUUID(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdatedByUUID) { // not required
		return nil
	}

	if err := validate.FormatOf("updatedByUuid", "body", "uuid", m.UpdatedByUUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ExceptionListResponse) validateUUID(formats strfmt.Registry) error {

	if swag.IsZero(m.UUID) { // not required
		return nil
	}

	if err := validate.FormatOf("uuid", "body", "uuid", m.UUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExceptionListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExceptionListResponse) UnmarshalBinary(b []byte) error {
	var res ExceptionListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
