// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GcpConnectorResponse GcpConnectorResponse
//
// swagger:model GcpConnectorResponse
type GcpConnectorResponse struct {

	// connector Id
	// Format: uuid
	ConnectorID strfmt.UUID `json:"connectorId,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// groups
	Groups []*Group `json:"groups"`

	// is disabled
	IsDisabled bool `json:"isDisabled,omitempty"`

	// last synced on
	LastSyncedOn string `json:"lastSyncedOn,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// next synced on
	NextSyncedOn string `json:"nextSyncedOn,omitempty"`

	// polling frequency
	PollingFrequency *RunFrequency `json:"pollingFrequency,omitempty"`

	// project Id
	ProjectID string `json:"projectId,omitempty"`

	// provider
	// Enum: [GCP]
	Provider string `json:"provider,omitempty"`

	// remediation enabled
	RemediationEnabled bool `json:"remediationEnabled,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// total assets
	TotalAssets int32 `json:"totalAssets,omitempty"`
}

// Validate validates this gcp connector response
func (m *GcpConnectorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectorID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroups(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePollingFrequency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpConnectorResponse) validateConnectorID(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectorID) { // not required
		return nil
	}

	if err := validate.FormatOf("connectorId", "body", "uuid", m.ConnectorID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GcpConnectorResponse) validateGroups(formats strfmt.Registry) error {

	if swag.IsZero(m.Groups) { // not required
		return nil
	}

	for i := 0; i < len(m.Groups); i++ {
		if swag.IsZero(m.Groups[i]) { // not required
			continue
		}

		if m.Groups[i] != nil {
			if err := m.Groups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("groups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GcpConnectorResponse) validatePollingFrequency(formats strfmt.Registry) error {

	if swag.IsZero(m.PollingFrequency) { // not required
		return nil
	}

	if m.PollingFrequency != nil {
		if err := m.PollingFrequency.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pollingFrequency")
			}
			return err
		}
	}

	return nil
}

var gcpConnectorResponseTypeProviderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["GCP"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		gcpConnectorResponseTypeProviderPropEnum = append(gcpConnectorResponseTypeProviderPropEnum, v)
	}
}

const (

	// GcpConnectorResponseProviderGCP captures enum value "GCP"
	GcpConnectorResponseProviderGCP string = "GCP"
)

// prop value enum
func (m *GcpConnectorResponse) validateProviderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, gcpConnectorResponseTypeProviderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GcpConnectorResponse) validateProvider(formats strfmt.Registry) error {

	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	// value enum
	if err := m.validateProviderEnum("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GcpConnectorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpConnectorResponse) UnmarshalBinary(b []byte) error {
	var res GcpConnectorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
