// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PagerdutyUpdateRequest PagerdutyUpdateRequest
//
// swagger:model PagerdutyUpdateRequest
type PagerdutyUpdateRequest struct {

	// action description
	ActionDescription string `json:"actionDescription,omitempty"`

	// action name
	ActionName string `json:"actionName,omitempty"`

	// client
	Client string `json:"client,omitempty"`

	// service key
	ServiceKey string `json:"serviceKey,omitempty"`

	// subject line
	SubjectLine string `json:"subjectLine,omitempty"`
}

// Validate validates this pagerduty update request
func (m *PagerdutyUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PagerdutyUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PagerdutyUpdateRequest) UnmarshalBinary(b []byte) error {
	var res PagerdutyUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
