/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// CreateUsingPOST2OKCode is the HTTP code returned for type CreateUsingPOST2OK
const CreateUsingPOST2OKCode int = 200

/*CreateUsingPOST2OK OK

swagger:response createUsingPOST2OK
*/
type CreateUsingPOST2OK struct {

	/*
	  In: Body
	*/
	Payload *models.GcpConnectorResponse `json:"body,omitempty"`
}

// NewCreateUsingPOST2OK creates CreateUsingPOST2OK with default headers values
func NewCreateUsingPOST2OK() *CreateUsingPOST2OK {

	return &CreateUsingPOST2OK{}
}

// WithPayload adds the payload to the create using p o s t2 o k response
func (o *CreateUsingPOST2OK) WithPayload(payload *models.GcpConnectorResponse) *CreateUsingPOST2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create using p o s t2 o k response
func (o *CreateUsingPOST2OK) SetPayload(payload *models.GcpConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUsingPOST2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUsingPOST2CreatedCode is the HTTP code returned for type CreateUsingPOST2Created
const CreateUsingPOST2CreatedCode int = 201

/*CreateUsingPOST2Created Created

swagger:response createUsingPOST2Created
*/
type CreateUsingPOST2Created struct {
}

// NewCreateUsingPOST2Created creates CreateUsingPOST2Created with default headers values
func NewCreateUsingPOST2Created() *CreateUsingPOST2Created {

	return &CreateUsingPOST2Created{}
}

// WriteResponse to the client
func (o *CreateUsingPOST2Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateUsingPOST2BadRequestCode is the HTTP code returned for type CreateUsingPOST2BadRequest
const CreateUsingPOST2BadRequestCode int = 400

/*CreateUsingPOST2BadRequest Bad Request

swagger:response createUsingPOST2BadRequest
*/
type CreateUsingPOST2BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewCreateUsingPOST2BadRequest creates CreateUsingPOST2BadRequest with default headers values
func NewCreateUsingPOST2BadRequest() *CreateUsingPOST2BadRequest {

	return &CreateUsingPOST2BadRequest{}
}

// WithPayload adds the payload to the create using p o s t2 bad request response
func (o *CreateUsingPOST2BadRequest) WithPayload(payload *models.APIErrorFacade) *CreateUsingPOST2BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create using p o s t2 bad request response
func (o *CreateUsingPOST2BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUsingPOST2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUsingPOST2UnauthorizedCode is the HTTP code returned for type CreateUsingPOST2Unauthorized
const CreateUsingPOST2UnauthorizedCode int = 401

/*CreateUsingPOST2Unauthorized Unauthorized user

swagger:response createUsingPOST2Unauthorized
*/
type CreateUsingPOST2Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewCreateUsingPOST2Unauthorized creates CreateUsingPOST2Unauthorized with default headers values
func NewCreateUsingPOST2Unauthorized() *CreateUsingPOST2Unauthorized {

	return &CreateUsingPOST2Unauthorized{}
}

// WithPayload adds the payload to the create using p o s t2 unauthorized response
func (o *CreateUsingPOST2Unauthorized) WithPayload(payload *models.APIErrorFacade) *CreateUsingPOST2Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create using p o s t2 unauthorized response
func (o *CreateUsingPOST2Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateUsingPOST2Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateUsingPOST2ForbiddenCode is the HTTP code returned for type CreateUsingPOST2Forbidden
const CreateUsingPOST2ForbiddenCode int = 403

/*CreateUsingPOST2Forbidden Forbidden

swagger:response createUsingPOST2Forbidden
*/
type CreateUsingPOST2Forbidden struct {
}

// NewCreateUsingPOST2Forbidden creates CreateUsingPOST2Forbidden with default headers values
func NewCreateUsingPOST2Forbidden() *CreateUsingPOST2Forbidden {

	return &CreateUsingPOST2Forbidden{}
}

// WriteResponse to the client
func (o *CreateUsingPOST2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateUsingPOST2NotFoundCode is the HTTP code returned for type CreateUsingPOST2NotFound
const CreateUsingPOST2NotFoundCode int = 404

/*CreateUsingPOST2NotFound Not Found

swagger:response createUsingPOST2NotFound
*/
type CreateUsingPOST2NotFound struct {
}

// NewCreateUsingPOST2NotFound creates CreateUsingPOST2NotFound with default headers values
func NewCreateUsingPOST2NotFound() *CreateUsingPOST2NotFound {

	return &CreateUsingPOST2NotFound{}
}

// WriteResponse to the client
func (o *CreateUsingPOST2NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
