/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// DeleteConnectorsUsingDELETE2OKCode is the HTTP code returned for type DeleteConnectorsUsingDELETE2OK
const DeleteConnectorsUsingDELETE2OKCode int = 200

/*DeleteConnectorsUsingDELETE2OK OK

swagger:response deleteConnectorsUsingDELETE2OK
*/
type DeleteConnectorsUsingDELETE2OK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewDeleteConnectorsUsingDELETE2OK creates DeleteConnectorsUsingDELETE2OK with default headers values
func NewDeleteConnectorsUsingDELETE2OK() *DeleteConnectorsUsingDELETE2OK {

	return &DeleteConnectorsUsingDELETE2OK{}
}

// WithPayload adds the payload to the delete connectors using d e l e t e2 o k response
func (o *DeleteConnectorsUsingDELETE2OK) WithPayload(payload interface{}) *DeleteConnectorsUsingDELETE2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connectors using d e l e t e2 o k response
func (o *DeleteConnectorsUsingDELETE2OK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorsUsingDELETE2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteConnectorsUsingDELETE2NoContentCode is the HTTP code returned for type DeleteConnectorsUsingDELETE2NoContent
const DeleteConnectorsUsingDELETE2NoContentCode int = 204

/*DeleteConnectorsUsingDELETE2NoContent No Content

swagger:response deleteConnectorsUsingDELETE2NoContent
*/
type DeleteConnectorsUsingDELETE2NoContent struct {
}

// NewDeleteConnectorsUsingDELETE2NoContent creates DeleteConnectorsUsingDELETE2NoContent with default headers values
func NewDeleteConnectorsUsingDELETE2NoContent() *DeleteConnectorsUsingDELETE2NoContent {

	return &DeleteConnectorsUsingDELETE2NoContent{}
}

// WriteResponse to the client
func (o *DeleteConnectorsUsingDELETE2NoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConnectorsUsingDELETE2BadRequestCode is the HTTP code returned for type DeleteConnectorsUsingDELETE2BadRequest
const DeleteConnectorsUsingDELETE2BadRequestCode int = 400

/*DeleteConnectorsUsingDELETE2BadRequest Bad Request

swagger:response deleteConnectorsUsingDELETE2BadRequest
*/
type DeleteConnectorsUsingDELETE2BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDeleteConnectorsUsingDELETE2BadRequest creates DeleteConnectorsUsingDELETE2BadRequest with default headers values
func NewDeleteConnectorsUsingDELETE2BadRequest() *DeleteConnectorsUsingDELETE2BadRequest {

	return &DeleteConnectorsUsingDELETE2BadRequest{}
}

// WithPayload adds the payload to the delete connectors using d e l e t e2 bad request response
func (o *DeleteConnectorsUsingDELETE2BadRequest) WithPayload(payload *models.APIErrorFacade) *DeleteConnectorsUsingDELETE2BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connectors using d e l e t e2 bad request response
func (o *DeleteConnectorsUsingDELETE2BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorsUsingDELETE2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConnectorsUsingDELETE2UnauthorizedCode is the HTTP code returned for type DeleteConnectorsUsingDELETE2Unauthorized
const DeleteConnectorsUsingDELETE2UnauthorizedCode int = 401

/*DeleteConnectorsUsingDELETE2Unauthorized Unauthorized user

swagger:response deleteConnectorsUsingDELETE2Unauthorized
*/
type DeleteConnectorsUsingDELETE2Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDeleteConnectorsUsingDELETE2Unauthorized creates DeleteConnectorsUsingDELETE2Unauthorized with default headers values
func NewDeleteConnectorsUsingDELETE2Unauthorized() *DeleteConnectorsUsingDELETE2Unauthorized {

	return &DeleteConnectorsUsingDELETE2Unauthorized{}
}

// WithPayload adds the payload to the delete connectors using d e l e t e2 unauthorized response
func (o *DeleteConnectorsUsingDELETE2Unauthorized) WithPayload(payload *models.APIErrorFacade) *DeleteConnectorsUsingDELETE2Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete connectors using d e l e t e2 unauthorized response
func (o *DeleteConnectorsUsingDELETE2Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConnectorsUsingDELETE2Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConnectorsUsingDELETE2ForbiddenCode is the HTTP code returned for type DeleteConnectorsUsingDELETE2Forbidden
const DeleteConnectorsUsingDELETE2ForbiddenCode int = 403

/*DeleteConnectorsUsingDELETE2Forbidden Forbidden

swagger:response deleteConnectorsUsingDELETE2Forbidden
*/
type DeleteConnectorsUsingDELETE2Forbidden struct {
}

// NewDeleteConnectorsUsingDELETE2Forbidden creates DeleteConnectorsUsingDELETE2Forbidden with default headers values
func NewDeleteConnectorsUsingDELETE2Forbidden() *DeleteConnectorsUsingDELETE2Forbidden {

	return &DeleteConnectorsUsingDELETE2Forbidden{}
}

// WriteResponse to the client
func (o *DeleteConnectorsUsingDELETE2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
