/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGcpErrorsListUsingGETHandlerFunc turns a function with the right signature into a get gcp errors list using g e t handler
type GetGcpErrorsListUsingGETHandlerFunc func(GetGcpErrorsListUsingGETParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGcpErrorsListUsingGETHandlerFunc) Handle(params GetGcpErrorsListUsingGETParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGcpErrorsListUsingGETHandler interface for that can handle valid get gcp errors list using g e t params
type GetGcpErrorsListUsingGETHandler interface {
	Handle(GetGcpErrorsListUsingGETParams, interface{}) middleware.Responder
}

// NewGetGcpErrorsListUsingGET creates a new http.Handler for the get gcp errors list using g e t operation
func NewGetGcpErrorsListUsingGET(ctx *middleware.Context, handler GetGcpErrorsListUsingGETHandler) *GetGcpErrorsListUsingGET {
	return &GetGcpErrorsListUsingGET{Context: ctx, Handler: handler}
}

/*GetGcpErrorsListUsingGET swagger:route GET /rest/v1/gcp/connectors/{connectorId}/errors GCP Connector getGcpErrorsListUsingGET

Get the list of errors encountered when executing GCP connector

*/
type GetGcpErrorsListUsingGET struct {
	Context *middleware.Context
	Handler GetGcpErrorsListUsingGETHandler
}

func (o *GetGcpErrorsListUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGcpErrorsListUsingGETParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
