/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDetailsUsingGET2HandlerFunc turns a function with the right signature into a get details using g e t 2 handler
type GetDetailsUsingGET2HandlerFunc func(GetDetailsUsingGET2Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDetailsUsingGET2HandlerFunc) Handle(params GetDetailsUsingGET2Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDetailsUsingGET2Handler interface for that can handle valid get details using g e t 2 params
type GetDetailsUsingGET2Handler interface {
	Handle(GetDetailsUsingGET2Params, interface{}) middleware.Responder
}

// NewGetDetailsUsingGET2 creates a new http.Handler for the get details using g e t 2 operation
func NewGetDetailsUsingGET2(ctx *middleware.Context, handler GetDetailsUsingGET2Handler) *GetDetailsUsingGET2 {
	return &GetDetailsUsingGET2{Context: ctx, Handler: handler}
}

/*GetDetailsUsingGET2 swagger:route GET /rest/v1/gcp/connectors/{connectorId} GCP Connector getDetailsUsingGET2

Get the details of connector

*/
type GetDetailsUsingGET2 struct {
	Context *middleware.Context
	Handler GetDetailsUsingGET2Handler
}

func (o *GetDetailsUsingGET2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDetailsUsingGET2Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
