/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RunConnectorUsingPOST2HandlerFunc turns a function with the right signature into a run connector using p o s t 2 handler
type RunConnectorUsingPOST2HandlerFunc func(RunConnectorUsingPOST2Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RunConnectorUsingPOST2HandlerFunc) Handle(params RunConnectorUsingPOST2Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RunConnectorUsingPOST2Handler interface for that can handle valid run connector using p o s t 2 params
type RunConnectorUsingPOST2Handler interface {
	Handle(RunConnectorUsingPOST2Params, interface{}) middleware.Responder
}

// NewRunConnectorUsingPOST2 creates a new http.Handler for the run connector using p o s t 2 operation
func NewRunConnectorUsingPOST2(ctx *middleware.Context, handler RunConnectorUsingPOST2Handler) *RunConnectorUsingPOST2 {
	return &RunConnectorUsingPOST2{Context: ctx, Handler: handler}
}

/*RunConnectorUsingPOST2 swagger:route POST /rest/v1/gcp/connectors/run GCP Connector runConnectorUsingPOST2

Run the provided connectors

*/
type RunConnectorUsingPOST2 struct {
	Context *middleware.Context
	Handler RunConnectorUsingPOST2Handler
}

func (o *RunConnectorUsingPOST2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRunConnectorUsingPOST2Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
