/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// UpdateConnectorUsingPUT2OKCode is the HTTP code returned for type UpdateConnectorUsingPUT2OK
const UpdateConnectorUsingPUT2OKCode int = 200

/*UpdateConnectorUsingPUT2OK OK

swagger:response updateConnectorUsingPUT2OK
*/
type UpdateConnectorUsingPUT2OK struct {

	/*
	  In: Body
	*/
	Payload *models.GcpConnectorResponse `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT2OK creates UpdateConnectorUsingPUT2OK with default headers values
func NewUpdateConnectorUsingPUT2OK() *UpdateConnectorUsingPUT2OK {

	return &UpdateConnectorUsingPUT2OK{}
}

// WithPayload adds the payload to the update connector using p u t2 o k response
func (o *UpdateConnectorUsingPUT2OK) WithPayload(payload *models.GcpConnectorResponse) *UpdateConnectorUsingPUT2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t2 o k response
func (o *UpdateConnectorUsingPUT2OK) SetPayload(payload *models.GcpConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT2CreatedCode is the HTTP code returned for type UpdateConnectorUsingPUT2Created
const UpdateConnectorUsingPUT2CreatedCode int = 201

/*UpdateConnectorUsingPUT2Created Created

swagger:response updateConnectorUsingPUT2Created
*/
type UpdateConnectorUsingPUT2Created struct {
}

// NewUpdateConnectorUsingPUT2Created creates UpdateConnectorUsingPUT2Created with default headers values
func NewUpdateConnectorUsingPUT2Created() *UpdateConnectorUsingPUT2Created {

	return &UpdateConnectorUsingPUT2Created{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// UpdateConnectorUsingPUT2BadRequestCode is the HTTP code returned for type UpdateConnectorUsingPUT2BadRequest
const UpdateConnectorUsingPUT2BadRequestCode int = 400

/*UpdateConnectorUsingPUT2BadRequest Bad Request

swagger:response updateConnectorUsingPUT2BadRequest
*/
type UpdateConnectorUsingPUT2BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT2BadRequest creates UpdateConnectorUsingPUT2BadRequest with default headers values
func NewUpdateConnectorUsingPUT2BadRequest() *UpdateConnectorUsingPUT2BadRequest {

	return &UpdateConnectorUsingPUT2BadRequest{}
}

// WithPayload adds the payload to the update connector using p u t2 bad request response
func (o *UpdateConnectorUsingPUT2BadRequest) WithPayload(payload *models.APIErrorFacade) *UpdateConnectorUsingPUT2BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t2 bad request response
func (o *UpdateConnectorUsingPUT2BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT2UnauthorizedCode is the HTTP code returned for type UpdateConnectorUsingPUT2Unauthorized
const UpdateConnectorUsingPUT2UnauthorizedCode int = 401

/*UpdateConnectorUsingPUT2Unauthorized Unauthorized user

swagger:response updateConnectorUsingPUT2Unauthorized
*/
type UpdateConnectorUsingPUT2Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT2Unauthorized creates UpdateConnectorUsingPUT2Unauthorized with default headers values
func NewUpdateConnectorUsingPUT2Unauthorized() *UpdateConnectorUsingPUT2Unauthorized {

	return &UpdateConnectorUsingPUT2Unauthorized{}
}

// WithPayload adds the payload to the update connector using p u t2 unauthorized response
func (o *UpdateConnectorUsingPUT2Unauthorized) WithPayload(payload *models.APIErrorFacade) *UpdateConnectorUsingPUT2Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t2 unauthorized response
func (o *UpdateConnectorUsingPUT2Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT2ForbiddenCode is the HTTP code returned for type UpdateConnectorUsingPUT2Forbidden
const UpdateConnectorUsingPUT2ForbiddenCode int = 403

/*UpdateConnectorUsingPUT2Forbidden Forbidden

swagger:response updateConnectorUsingPUT2Forbidden
*/
type UpdateConnectorUsingPUT2Forbidden struct {
}

// NewUpdateConnectorUsingPUT2Forbidden creates UpdateConnectorUsingPUT2Forbidden with default headers values
func NewUpdateConnectorUsingPUT2Forbidden() *UpdateConnectorUsingPUT2Forbidden {

	return &UpdateConnectorUsingPUT2Forbidden{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UpdateConnectorUsingPUT2NotFoundCode is the HTTP code returned for type UpdateConnectorUsingPUT2NotFound
const UpdateConnectorUsingPUT2NotFoundCode int = 404

/*UpdateConnectorUsingPUT2NotFound Not Found

swagger:response updateConnectorUsingPUT2NotFound
*/
type UpdateConnectorUsingPUT2NotFound struct {
}

// NewUpdateConnectorUsingPUT2NotFound creates UpdateConnectorUsingPUT2NotFound with default headers values
func NewUpdateConnectorUsingPUT2NotFound() *UpdateConnectorUsingPUT2NotFound {

	return &UpdateConnectorUsingPUT2NotFound{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT2NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
