/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateConnectorUsingPUT2HandlerFunc turns a function with the right signature into a update connector using p u t 2 handler
type UpdateConnectorUsingPUT2HandlerFunc func(UpdateConnectorUsingPUT2Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConnectorUsingPUT2HandlerFunc) Handle(params UpdateConnectorUsingPUT2Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateConnectorUsingPUT2Handler interface for that can handle valid update connector using p u t 2 params
type UpdateConnectorUsingPUT2Handler interface {
	Handle(UpdateConnectorUsingPUT2Params, interface{}) middleware.Responder
}

// NewUpdateConnectorUsingPUT2 creates a new http.Handler for the update connector using p u t 2 operation
func NewUpdateConnectorUsingPUT2(ctx *middleware.Context, handler UpdateConnectorUsingPUT2Handler) *UpdateConnectorUsingPUT2 {
	return &UpdateConnectorUsingPUT2{Context: ctx, Handler: handler}
}

/*UpdateConnectorUsingPUT2 swagger:route PUT /rest/v1/gcp/connectors/{connectorId} GCP Connector updateConnectorUsingPUT2

Update the existing connector

*/
type UpdateConnectorUsingPUT2 struct {
	Context *middleware.Context
	Handler UpdateConnectorUsingPUT2Handler
}

func (o *UpdateConnectorUsingPUT2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateConnectorUsingPUT2Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
