swagger_codegen_version="v0.25.0"
swagger_image="/app quay.io/goswagger/swagger:${swagger_codegen_version}"

# Generate Service Models
rm -Rf ./swagger/models
docker run --rm --network none  \
  --user "$(id -u):$(id -g)" \
  -e GOFLAGS=-mod=vendor -v "$(pwd):/app" -w ${swagger_image} generate model -f ./swagger/swagger.json -t ./swagger

for f in $(find ./swagger/models -type f -name "*.go"); do
    sed -i '/^\/\/ Code generated by/s/^/\/\* #nosec \*\//' ${f}
done

# Generate Server
rm -Rf ./swagger/server
docker run --rm --network none  \
  --user "$(id -u):$(id -g)" \
  -e GOFLAGS=-mod=vendor -v "$(pwd):/app" -w ${swagger_image} generate server -f ./swagger/swagger.json --exclude-main --server-package server --exclude-spec -t ./swagger

for f in $(find ./swagger/server -type f -name "*.go"); do
    sed -i '/^\/\/ Code generated by/s/^/\/\* #nosec \*\//' ${f}
done

go mod tidy