/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// DownloadAwsCloudFormationTemplateUsingGETOKCode is the HTTP code returned for type DownloadAwsCloudFormationTemplateUsingGETOK
const DownloadAwsCloudFormationTemplateUsingGETOKCode int = 200

/*DownloadAwsCloudFormationTemplateUsingGETOK OK

swagger:response downloadAwsCloudFormationTemplateUsingGETOK
*/
type DownloadAwsCloudFormationTemplateUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewDownloadAwsCloudFormationTemplateUsingGETOK creates DownloadAwsCloudFormationTemplateUsingGETOK with default headers values
func NewDownloadAwsCloudFormationTemplateUsingGETOK() *DownloadAwsCloudFormationTemplateUsingGETOK {

	return &DownloadAwsCloudFormationTemplateUsingGETOK{}
}

// WithPayload adds the payload to the download aws cloud formation template using g e t o k response
func (o *DownloadAwsCloudFormationTemplateUsingGETOK) WithPayload(payload *models.Resource) *DownloadAwsCloudFormationTemplateUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download aws cloud formation template using g e t o k response
func (o *DownloadAwsCloudFormationTemplateUsingGETOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadAwsCloudFormationTemplateUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadAwsCloudFormationTemplateUsingGETBadRequestCode is the HTTP code returned for type DownloadAwsCloudFormationTemplateUsingGETBadRequest
const DownloadAwsCloudFormationTemplateUsingGETBadRequestCode int = 400

/*DownloadAwsCloudFormationTemplateUsingGETBadRequest Bad Request

swagger:response downloadAwsCloudFormationTemplateUsingGETBadRequest
*/
type DownloadAwsCloudFormationTemplateUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDownloadAwsCloudFormationTemplateUsingGETBadRequest creates DownloadAwsCloudFormationTemplateUsingGETBadRequest with default headers values
func NewDownloadAwsCloudFormationTemplateUsingGETBadRequest() *DownloadAwsCloudFormationTemplateUsingGETBadRequest {

	return &DownloadAwsCloudFormationTemplateUsingGETBadRequest{}
}

// WithPayload adds the payload to the download aws cloud formation template using g e t bad request response
func (o *DownloadAwsCloudFormationTemplateUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *DownloadAwsCloudFormationTemplateUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download aws cloud formation template using g e t bad request response
func (o *DownloadAwsCloudFormationTemplateUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadAwsCloudFormationTemplateUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadAwsCloudFormationTemplateUsingGETUnauthorizedCode is the HTTP code returned for type DownloadAwsCloudFormationTemplateUsingGETUnauthorized
const DownloadAwsCloudFormationTemplateUsingGETUnauthorizedCode int = 401

/*DownloadAwsCloudFormationTemplateUsingGETUnauthorized Unauthorized user

swagger:response downloadAwsCloudFormationTemplateUsingGETUnauthorized
*/
type DownloadAwsCloudFormationTemplateUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewDownloadAwsCloudFormationTemplateUsingGETUnauthorized creates DownloadAwsCloudFormationTemplateUsingGETUnauthorized with default headers values
func NewDownloadAwsCloudFormationTemplateUsingGETUnauthorized() *DownloadAwsCloudFormationTemplateUsingGETUnauthorized {

	return &DownloadAwsCloudFormationTemplateUsingGETUnauthorized{}
}

// WithPayload adds the payload to the download aws cloud formation template using g e t unauthorized response
func (o *DownloadAwsCloudFormationTemplateUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *DownloadAwsCloudFormationTemplateUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the download aws cloud formation template using g e t unauthorized response
func (o *DownloadAwsCloudFormationTemplateUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DownloadAwsCloudFormationTemplateUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DownloadAwsCloudFormationTemplateUsingGETForbiddenCode is the HTTP code returned for type DownloadAwsCloudFormationTemplateUsingGETForbidden
const DownloadAwsCloudFormationTemplateUsingGETForbiddenCode int = 403

/*DownloadAwsCloudFormationTemplateUsingGETForbidden Forbidden

swagger:response downloadAwsCloudFormationTemplateUsingGETForbidden
*/
type DownloadAwsCloudFormationTemplateUsingGETForbidden struct {
}

// NewDownloadAwsCloudFormationTemplateUsingGETForbidden creates DownloadAwsCloudFormationTemplateUsingGETForbidden with default headers values
func NewDownloadAwsCloudFormationTemplateUsingGETForbidden() *DownloadAwsCloudFormationTemplateUsingGETForbidden {

	return &DownloadAwsCloudFormationTemplateUsingGETForbidden{}
}

// WriteResponse to the client
func (o *DownloadAwsCloudFormationTemplateUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DownloadAwsCloudFormationTemplateUsingGETNotFoundCode is the HTTP code returned for type DownloadAwsCloudFormationTemplateUsingGETNotFound
const DownloadAwsCloudFormationTemplateUsingGETNotFoundCode int = 404

/*DownloadAwsCloudFormationTemplateUsingGETNotFound Not Found

swagger:response downloadAwsCloudFormationTemplateUsingGETNotFound
*/
type DownloadAwsCloudFormationTemplateUsingGETNotFound struct {
}

// NewDownloadAwsCloudFormationTemplateUsingGETNotFound creates DownloadAwsCloudFormationTemplateUsingGETNotFound with default headers values
func NewDownloadAwsCloudFormationTemplateUsingGETNotFound() *DownloadAwsCloudFormationTemplateUsingGETNotFound {

	return &DownloadAwsCloudFormationTemplateUsingGETNotFound{}
}

// WriteResponse to the client
func (o *DownloadAwsCloudFormationTemplateUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
