/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetAwsAccountIDUsingGETOKCode is the HTTP code returned for type GetAwsAccountIDUsingGETOK
const GetAwsAccountIDUsingGETOKCode int = 200

/*GetAwsAccountIDUsingGETOK OK

swagger:response getAwsAccountIdUsingGETOK
*/
type GetAwsAccountIDUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload map[string]string `json:"body,omitempty"`
}

// NewGetAwsAccountIDUsingGETOK creates GetAwsAccountIDUsingGETOK with default headers values
func NewGetAwsAccountIDUsingGETOK() *GetAwsAccountIDUsingGETOK {

	return &GetAwsAccountIDUsingGETOK{}
}

// WithPayload adds the payload to the get aws account Id using g e t o k response
func (o *GetAwsAccountIDUsingGETOK) WithPayload(payload map[string]string) *GetAwsAccountIDUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get aws account Id using g e t o k response
func (o *GetAwsAccountIDUsingGETOK) SetPayload(payload map[string]string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAwsAccountIDUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]string, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAwsAccountIDUsingGETBadRequestCode is the HTTP code returned for type GetAwsAccountIDUsingGETBadRequest
const GetAwsAccountIDUsingGETBadRequestCode int = 400

/*GetAwsAccountIDUsingGETBadRequest Bad Request

swagger:response getAwsAccountIdUsingGETBadRequest
*/
type GetAwsAccountIDUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetAwsAccountIDUsingGETBadRequest creates GetAwsAccountIDUsingGETBadRequest with default headers values
func NewGetAwsAccountIDUsingGETBadRequest() *GetAwsAccountIDUsingGETBadRequest {

	return &GetAwsAccountIDUsingGETBadRequest{}
}

// WithPayload adds the payload to the get aws account Id using g e t bad request response
func (o *GetAwsAccountIDUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *GetAwsAccountIDUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get aws account Id using g e t bad request response
func (o *GetAwsAccountIDUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAwsAccountIDUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAwsAccountIDUsingGETUnauthorizedCode is the HTTP code returned for type GetAwsAccountIDUsingGETUnauthorized
const GetAwsAccountIDUsingGETUnauthorizedCode int = 401

/*GetAwsAccountIDUsingGETUnauthorized Unauthorized user

swagger:response getAwsAccountIdUsingGETUnauthorized
*/
type GetAwsAccountIDUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetAwsAccountIDUsingGETUnauthorized creates GetAwsAccountIDUsingGETUnauthorized with default headers values
func NewGetAwsAccountIDUsingGETUnauthorized() *GetAwsAccountIDUsingGETUnauthorized {

	return &GetAwsAccountIDUsingGETUnauthorized{}
}

// WithPayload adds the payload to the get aws account Id using g e t unauthorized response
func (o *GetAwsAccountIDUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *GetAwsAccountIDUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get aws account Id using g e t unauthorized response
func (o *GetAwsAccountIDUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAwsAccountIDUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAwsAccountIDUsingGETForbiddenCode is the HTTP code returned for type GetAwsAccountIDUsingGETForbidden
const GetAwsAccountIDUsingGETForbiddenCode int = 403

/*GetAwsAccountIDUsingGETForbidden Forbidden

swagger:response getAwsAccountIdUsingGETForbidden
*/
type GetAwsAccountIDUsingGETForbidden struct {
}

// NewGetAwsAccountIDUsingGETForbidden creates GetAwsAccountIDUsingGETForbidden with default headers values
func NewGetAwsAccountIDUsingGETForbidden() *GetAwsAccountIDUsingGETForbidden {

	return &GetAwsAccountIDUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetAwsAccountIDUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetAwsAccountIDUsingGETNotFoundCode is the HTTP code returned for type GetAwsAccountIDUsingGETNotFound
const GetAwsAccountIDUsingGETNotFoundCode int = 404

/*GetAwsAccountIDUsingGETNotFound Not Found

swagger:response getAwsAccountIdUsingGETNotFound
*/
type GetAwsAccountIDUsingGETNotFound struct {
}

// NewGetAwsAccountIDUsingGETNotFound creates GetAwsAccountIDUsingGETNotFound with default headers values
func NewGetAwsAccountIDUsingGETNotFound() *GetAwsAccountIDUsingGETNotFound {

	return &GetAwsAccountIDUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetAwsAccountIDUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
