/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetDetailsUsingGET1Params creates a new GetDetailsUsingGET1Params object
// no default values defined in spec.
func NewGetDetailsUsingGET1Params() GetDetailsUsingGET1Params {

	return GetDetailsUsingGET1Params{}
}

// GetDetailsUsingGET1Params contains all the bound params for the get details using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDetailsUsingGET_1
type GetDetailsUsingGET1Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the connector ID of a specific connector in the user’s scope.
	  Required: true
	  In: path
	*/
	ConnectorID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDetailsUsingGET1Params() beforehand.
func (o *GetDetailsUsingGET1Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rConnectorID, rhkConnectorID, _ := route.Params.GetOK("connectorId")
	if err := o.bindConnectorID(rConnectorID, rhkConnectorID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindConnectorID binds and validates parameter ConnectorID from path.
func (o *GetDetailsUsingGET1Params) bindConnectorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ConnectorID = raw

	return nil
}
