/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDetailsUsingGET1HandlerFunc turns a function with the right signature into a get details using g e t 1 handler
type GetDetailsUsingGET1HandlerFunc func(GetDetailsUsingGET1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDetailsUsingGET1HandlerFunc) Handle(params GetDetailsUsingGET1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDetailsUsingGET1Handler interface for that can handle valid get details using g e t 1 params
type GetDetailsUsingGET1Handler interface {
	Handle(GetDetailsUsingGET1Params, interface{}) middleware.Responder
}

// NewGetDetailsUsingGET1 creates a new http.Handler for the get details using g e t 1 operation
func NewGetDetailsUsingGET1(ctx *middleware.Context, handler GetDetailsUsingGET1Handler) *GetDetailsUsingGET1 {
	return &GetDetailsUsingGET1{Context: ctx, Handler: handler}
}

/*GetDetailsUsingGET1 swagger:route GET /rest/v1/aws/connectors/{connectorId} AWS Connector getDetailsUsingGET1

Get the details of connector

*/
type GetDetailsUsingGET1 struct {
	Context *middleware.Context
	Handler GetDetailsUsingGET1Handler
}

func (o *GetDetailsUsingGET1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDetailsUsingGET1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
