/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetErrorsListUsingGETURL generates an URL for the get errors list using g e t operation
type GetErrorsListUsingGETURL struct {
	ConnectorID string

	PageNo   int32
	PageSize int32

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetErrorsListUsingGETURL) WithBasePath(bp string) *GetErrorsListUsingGETURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetErrorsListUsingGETURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetErrorsListUsingGETURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/rest/v1/aws/connectors/{connectorId}/errors"

	connectorID := o.ConnectorID
	if connectorID != "" {
		_path = strings.Replace(_path, "{connectorId}", connectorID, -1)
	} else {
		return nil, errors.New("connectorId is required on GetErrorsListUsingGETURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/cloudview-api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	pageNoQ := swag.FormatInt32(o.PageNo)
	if pageNoQ != "" {
		qs.Set("pageNo", pageNoQ)
	}

	pageSizeQ := swag.FormatInt32(o.PageSize)
	if pageSizeQ != "" {
		qs.Set("pageSize", pageSizeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetErrorsListUsingGETURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetErrorsListUsingGETURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetErrorsListUsingGETURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetErrorsListUsingGETURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetErrorsListUsingGETURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetErrorsListUsingGETURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
