/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetListUsingGET1OKCode is the HTTP code returned for type GetListUsingGET1OK
const GetListUsingGET1OKCode int = 200

/*GetListUsingGET1OK OK

swagger:response getListUsingGET1OK
*/
type GetListUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.PageImplAwsConnectorResponse `json:"body,omitempty"`
}

// NewGetListUsingGET1OK creates GetListUsingGET1OK with default headers values
func NewGetListUsingGET1OK() *GetListUsingGET1OK {

	return &GetListUsingGET1OK{}
}

// WithPayload adds the payload to the get list using g e t1 o k response
func (o *GetListUsingGET1OK) WithPayload(payload *models.PageImplAwsConnectorResponse) *GetListUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t1 o k response
func (o *GetListUsingGET1OK) SetPayload(payload *models.PageImplAwsConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGET1BadRequestCode is the HTTP code returned for type GetListUsingGET1BadRequest
const GetListUsingGET1BadRequestCode int = 400

/*GetListUsingGET1BadRequest Bad Request

swagger:response getListUsingGET1BadRequest
*/
type GetListUsingGET1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetListUsingGET1BadRequest creates GetListUsingGET1BadRequest with default headers values
func NewGetListUsingGET1BadRequest() *GetListUsingGET1BadRequest {

	return &GetListUsingGET1BadRequest{}
}

// WithPayload adds the payload to the get list using g e t1 bad request response
func (o *GetListUsingGET1BadRequest) WithPayload(payload *models.APIErrorFacade) *GetListUsingGET1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t1 bad request response
func (o *GetListUsingGET1BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGET1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGET1UnauthorizedCode is the HTTP code returned for type GetListUsingGET1Unauthorized
const GetListUsingGET1UnauthorizedCode int = 401

/*GetListUsingGET1Unauthorized Unauthorized user

swagger:response getListUsingGET1Unauthorized
*/
type GetListUsingGET1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetListUsingGET1Unauthorized creates GetListUsingGET1Unauthorized with default headers values
func NewGetListUsingGET1Unauthorized() *GetListUsingGET1Unauthorized {

	return &GetListUsingGET1Unauthorized{}
}

// WithPayload adds the payload to the get list using g e t1 unauthorized response
func (o *GetListUsingGET1Unauthorized) WithPayload(payload *models.APIErrorFacade) *GetListUsingGET1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list using g e t1 unauthorized response
func (o *GetListUsingGET1Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListUsingGET1ForbiddenCode is the HTTP code returned for type GetListUsingGET1Forbidden
const GetListUsingGET1ForbiddenCode int = 403

/*GetListUsingGET1Forbidden Forbidden

swagger:response getListUsingGET1Forbidden
*/
type GetListUsingGET1Forbidden struct {
}

// NewGetListUsingGET1Forbidden creates GetListUsingGET1Forbidden with default headers values
func NewGetListUsingGET1Forbidden() *GetListUsingGET1Forbidden {

	return &GetListUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *GetListUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetListUsingGET1NotFoundCode is the HTTP code returned for type GetListUsingGET1NotFound
const GetListUsingGET1NotFoundCode int = 404

/*GetListUsingGET1NotFound Not Found

swagger:response getListUsingGET1NotFound
*/
type GetListUsingGET1NotFound struct {
}

// NewGetListUsingGET1NotFound creates GetListUsingGET1NotFound with default headers values
func NewGetListUsingGET1NotFound() *GetListUsingGET1NotFound {

	return &GetListUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *GetListUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
