/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetErrorsListUsingGETOKCode is the HTTP code returned for type GetErrorsListUsingGETOK
const GetErrorsListUsingGETOKCode int = 200

/*GetErrorsListUsingGETOK OK

swagger:response getErrorsListUsingGETOK
*/
type GetErrorsListUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.PageImplAwsConnectorErrorResponse `json:"body,omitempty"`
}

// NewGetErrorsListUsingGETOK creates GetErrorsListUsingGETOK with default headers values
func NewGetErrorsListUsingGETOK() *GetErrorsListUsingGETOK {

	return &GetErrorsListUsingGETOK{}
}

// WithPayload adds the payload to the get errors list using g e t o k response
func (o *GetErrorsListUsingGETOK) WithPayload(payload *models.PageImplAwsConnectorErrorResponse) *GetErrorsListUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get errors list using g e t o k response
func (o *GetErrorsListUsingGETOK) SetPayload(payload *models.PageImplAwsConnectorErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetErrorsListUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetErrorsListUsingGETBadRequestCode is the HTTP code returned for type GetErrorsListUsingGETBadRequest
const GetErrorsListUsingGETBadRequestCode int = 400

/*GetErrorsListUsingGETBadRequest Bad Request

swagger:response getErrorsListUsingGETBadRequest
*/
type GetErrorsListUsingGETBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetErrorsListUsingGETBadRequest creates GetErrorsListUsingGETBadRequest with default headers values
func NewGetErrorsListUsingGETBadRequest() *GetErrorsListUsingGETBadRequest {

	return &GetErrorsListUsingGETBadRequest{}
}

// WithPayload adds the payload to the get errors list using g e t bad request response
func (o *GetErrorsListUsingGETBadRequest) WithPayload(payload *models.APIErrorFacade) *GetErrorsListUsingGETBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get errors list using g e t bad request response
func (o *GetErrorsListUsingGETBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetErrorsListUsingGETBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetErrorsListUsingGETUnauthorizedCode is the HTTP code returned for type GetErrorsListUsingGETUnauthorized
const GetErrorsListUsingGETUnauthorizedCode int = 401

/*GetErrorsListUsingGETUnauthorized Unauthorized user

swagger:response getErrorsListUsingGETUnauthorized
*/
type GetErrorsListUsingGETUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetErrorsListUsingGETUnauthorized creates GetErrorsListUsingGETUnauthorized with default headers values
func NewGetErrorsListUsingGETUnauthorized() *GetErrorsListUsingGETUnauthorized {

	return &GetErrorsListUsingGETUnauthorized{}
}

// WithPayload adds the payload to the get errors list using g e t unauthorized response
func (o *GetErrorsListUsingGETUnauthorized) WithPayload(payload *models.APIErrorFacade) *GetErrorsListUsingGETUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get errors list using g e t unauthorized response
func (o *GetErrorsListUsingGETUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetErrorsListUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetErrorsListUsingGETForbiddenCode is the HTTP code returned for type GetErrorsListUsingGETForbidden
const GetErrorsListUsingGETForbiddenCode int = 403

/*GetErrorsListUsingGETForbidden Forbidden

swagger:response getErrorsListUsingGETForbidden
*/
type GetErrorsListUsingGETForbidden struct {
}

// NewGetErrorsListUsingGETForbidden creates GetErrorsListUsingGETForbidden with default headers values
func NewGetErrorsListUsingGETForbidden() *GetErrorsListUsingGETForbidden {

	return &GetErrorsListUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetErrorsListUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetErrorsListUsingGETNotFoundCode is the HTTP code returned for type GetErrorsListUsingGETNotFound
const GetErrorsListUsingGETNotFoundCode int = 404

/*GetErrorsListUsingGETNotFound Not Found

swagger:response getErrorsListUsingGETNotFound
*/
type GetErrorsListUsingGETNotFound struct {
}

// NewGetErrorsListUsingGETNotFound creates GetErrorsListUsingGETNotFound with default headers values
func NewGetErrorsListUsingGETNotFound() *GetErrorsListUsingGETNotFound {

	return &GetErrorsListUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetErrorsListUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
