/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetListUsingGET1HandlerFunc turns a function with the right signature into a get list using g e t 1 handler
type GetListUsingGET1HandlerFunc func(GetListUsingGET1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetListUsingGET1HandlerFunc) Handle(params GetListUsingGET1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetListUsingGET1Handler interface for that can handle valid get list using g e t 1 params
type GetListUsingGET1Handler interface {
	Handle(GetListUsingGET1Params, interface{}) middleware.Responder
}

// NewGetListUsingGET1 creates a new http.Handler for the get list using g e t 1 operation
func NewGetListUsingGET1(ctx *middleware.Context, handler GetListUsingGET1Handler) *GetListUsingGET1 {
	return &GetListUsingGET1{Context: ctx, Handler: handler}
}

/*GetListUsingGET1 swagger:route GET /rest/v1/aws/connectors AWS Connector getListUsingGET1

Get the list of connectors

*/
type GetListUsingGET1 struct {
	Context *middleware.Context
	Handler GetListUsingGET1Handler
}

func (o *GetListUsingGET1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetListUsingGET1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
