/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetErrorsListUsingGETHandlerFunc turns a function with the right signature into a get errors list using g e t handler
type GetErrorsListUsingGETHandlerFunc func(GetErrorsListUsingGETParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetErrorsListUsingGETHandlerFunc) Handle(params GetErrorsListUsingGETParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetErrorsListUsingGETHandler interface for that can handle valid get errors list using g e t params
type GetErrorsListUsingGETHandler interface {
	Handle(GetErrorsListUsingGETParams, interface{}) middleware.Responder
}

// NewGetErrorsListUsingGET creates a new http.Handler for the get errors list using g e t operation
func NewGetErrorsListUsingGET(ctx *middleware.Context, handler GetErrorsListUsingGETHandler) *GetErrorsListUsingGET {
	return &GetErrorsListUsingGET{Context: ctx, Handler: handler}
}

/*GetErrorsListUsingGET swagger:route GET /rest/v1/aws/connectors/{connectorId}/errors AWS Connector getErrorsListUsingGET

Get the list of errors encountered when executing AWS connector

*/
type GetErrorsListUsingGET struct {
	Context *middleware.Context
	Handler GetErrorsListUsingGETHandler
}

func (o *GetErrorsListUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetErrorsListUsingGETParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
