/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetDetailsUsingGET1OKCode is the HTTP code returned for type GetDetailsUsingGET1OK
const GetDetailsUsingGET1OKCode int = 200

/*GetDetailsUsingGET1OK OK

swagger:response getDetailsUsingGET1OK
*/
type GetDetailsUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.AwsConnectorResponse `json:"body,omitempty"`
}

// NewGetDetailsUsingGET1OK creates GetDetailsUsingGET1OK with default headers values
func NewGetDetailsUsingGET1OK() *GetDetailsUsingGET1OK {

	return &GetDetailsUsingGET1OK{}
}

// WithPayload adds the payload to the get details using g e t1 o k response
func (o *GetDetailsUsingGET1OK) WithPayload(payload *models.AwsConnectorResponse) *GetDetailsUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get details using g e t1 o k response
func (o *GetDetailsUsingGET1OK) SetPayload(payload *models.AwsConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDetailsUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDetailsUsingGET1BadRequestCode is the HTTP code returned for type GetDetailsUsingGET1BadRequest
const GetDetailsUsingGET1BadRequestCode int = 400

/*GetDetailsUsingGET1BadRequest Bad Request

swagger:response getDetailsUsingGET1BadRequest
*/
type GetDetailsUsingGET1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetDetailsUsingGET1BadRequest creates GetDetailsUsingGET1BadRequest with default headers values
func NewGetDetailsUsingGET1BadRequest() *GetDetailsUsingGET1BadRequest {

	return &GetDetailsUsingGET1BadRequest{}
}

// WithPayload adds the payload to the get details using g e t1 bad request response
func (o *GetDetailsUsingGET1BadRequest) WithPayload(payload *models.APIErrorFacade) *GetDetailsUsingGET1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get details using g e t1 bad request response
func (o *GetDetailsUsingGET1BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDetailsUsingGET1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDetailsUsingGET1UnauthorizedCode is the HTTP code returned for type GetDetailsUsingGET1Unauthorized
const GetDetailsUsingGET1UnauthorizedCode int = 401

/*GetDetailsUsingGET1Unauthorized Unauthorized user

swagger:response getDetailsUsingGET1Unauthorized
*/
type GetDetailsUsingGET1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetDetailsUsingGET1Unauthorized creates GetDetailsUsingGET1Unauthorized with default headers values
func NewGetDetailsUsingGET1Unauthorized() *GetDetailsUsingGET1Unauthorized {

	return &GetDetailsUsingGET1Unauthorized{}
}

// WithPayload adds the payload to the get details using g e t1 unauthorized response
func (o *GetDetailsUsingGET1Unauthorized) WithPayload(payload *models.APIErrorFacade) *GetDetailsUsingGET1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get details using g e t1 unauthorized response
func (o *GetDetailsUsingGET1Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDetailsUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDetailsUsingGET1ForbiddenCode is the HTTP code returned for type GetDetailsUsingGET1Forbidden
const GetDetailsUsingGET1ForbiddenCode int = 403

/*GetDetailsUsingGET1Forbidden Forbidden

swagger:response getDetailsUsingGET1Forbidden
*/
type GetDetailsUsingGET1Forbidden struct {
}

// NewGetDetailsUsingGET1Forbidden creates GetDetailsUsingGET1Forbidden with default headers values
func NewGetDetailsUsingGET1Forbidden() *GetDetailsUsingGET1Forbidden {

	return &GetDetailsUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *GetDetailsUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetDetailsUsingGET1NotFoundCode is the HTTP code returned for type GetDetailsUsingGET1NotFound
const GetDetailsUsingGET1NotFoundCode int = 404

/*GetDetailsUsingGET1NotFound Not Found

swagger:response getDetailsUsingGET1NotFound
*/
type GetDetailsUsingGET1NotFound struct {
}

// NewGetDetailsUsingGET1NotFound creates GetDetailsUsingGET1NotFound with default headers values
func NewGetDetailsUsingGET1NotFound() *GetDetailsUsingGET1NotFound {

	return &GetDetailsUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *GetDetailsUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
