/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RunConnectorUsingPOST1HandlerFunc turns a function with the right signature into a run connector using p o s t 1 handler
type RunConnectorUsingPOST1HandlerFunc func(RunConnectorUsingPOST1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RunConnectorUsingPOST1HandlerFunc) Handle(params RunConnectorUsingPOST1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RunConnectorUsingPOST1Handler interface for that can handle valid run connector using p o s t 1 params
type RunConnectorUsingPOST1Handler interface {
	Handle(RunConnectorUsingPOST1Params, interface{}) middleware.Responder
}

// NewRunConnectorUsingPOST1 creates a new http.Handler for the run connector using p o s t 1 operation
func NewRunConnectorUsingPOST1(ctx *middleware.Context, handler RunConnectorUsingPOST1Handler) *RunConnectorUsingPOST1 {
	return &RunConnectorUsingPOST1{Context: ctx, Handler: handler}
}

/*RunConnectorUsingPOST1 swagger:route POST /rest/v1/aws/connectors/run AWS Connector runConnectorUsingPOST1

Run the provided connectors

*/
type RunConnectorUsingPOST1 struct {
	Context *middleware.Context
	Handler RunConnectorUsingPOST1Handler
}

func (o *RunConnectorUsingPOST1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRunConnectorUsingPOST1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
