/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// UpdateConnectorUsingPUT1OKCode is the HTTP code returned for type UpdateConnectorUsingPUT1OK
const UpdateConnectorUsingPUT1OKCode int = 200

/*UpdateConnectorUsingPUT1OK OK

swagger:response updateConnectorUsingPUT1OK
*/
type UpdateConnectorUsingPUT1OK struct {

	/*
	  In: Body
	*/
	Payload *models.AwsConnectorResponse `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT1OK creates UpdateConnectorUsingPUT1OK with default headers values
func NewUpdateConnectorUsingPUT1OK() *UpdateConnectorUsingPUT1OK {

	return &UpdateConnectorUsingPUT1OK{}
}

// WithPayload adds the payload to the update connector using p u t1 o k response
func (o *UpdateConnectorUsingPUT1OK) WithPayload(payload *models.AwsConnectorResponse) *UpdateConnectorUsingPUT1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t1 o k response
func (o *UpdateConnectorUsingPUT1OK) SetPayload(payload *models.AwsConnectorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT1CreatedCode is the HTTP code returned for type UpdateConnectorUsingPUT1Created
const UpdateConnectorUsingPUT1CreatedCode int = 201

/*UpdateConnectorUsingPUT1Created Created

swagger:response updateConnectorUsingPUT1Created
*/
type UpdateConnectorUsingPUT1Created struct {
}

// NewUpdateConnectorUsingPUT1Created creates UpdateConnectorUsingPUT1Created with default headers values
func NewUpdateConnectorUsingPUT1Created() *UpdateConnectorUsingPUT1Created {

	return &UpdateConnectorUsingPUT1Created{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// UpdateConnectorUsingPUT1BadRequestCode is the HTTP code returned for type UpdateConnectorUsingPUT1BadRequest
const UpdateConnectorUsingPUT1BadRequestCode int = 400

/*UpdateConnectorUsingPUT1BadRequest Bad Request

swagger:response updateConnectorUsingPUT1BadRequest
*/
type UpdateConnectorUsingPUT1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT1BadRequest creates UpdateConnectorUsingPUT1BadRequest with default headers values
func NewUpdateConnectorUsingPUT1BadRequest() *UpdateConnectorUsingPUT1BadRequest {

	return &UpdateConnectorUsingPUT1BadRequest{}
}

// WithPayload adds the payload to the update connector using p u t1 bad request response
func (o *UpdateConnectorUsingPUT1BadRequest) WithPayload(payload *models.APIErrorFacade) *UpdateConnectorUsingPUT1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t1 bad request response
func (o *UpdateConnectorUsingPUT1BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT1UnauthorizedCode is the HTTP code returned for type UpdateConnectorUsingPUT1Unauthorized
const UpdateConnectorUsingPUT1UnauthorizedCode int = 401

/*UpdateConnectorUsingPUT1Unauthorized Unauthorized user

swagger:response updateConnectorUsingPUT1Unauthorized
*/
type UpdateConnectorUsingPUT1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateConnectorUsingPUT1Unauthorized creates UpdateConnectorUsingPUT1Unauthorized with default headers values
func NewUpdateConnectorUsingPUT1Unauthorized() *UpdateConnectorUsingPUT1Unauthorized {

	return &UpdateConnectorUsingPUT1Unauthorized{}
}

// WithPayload adds the payload to the update connector using p u t1 unauthorized response
func (o *UpdateConnectorUsingPUT1Unauthorized) WithPayload(payload *models.APIErrorFacade) *UpdateConnectorUsingPUT1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update connector using p u t1 unauthorized response
func (o *UpdateConnectorUsingPUT1Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConnectorUsingPUT1ForbiddenCode is the HTTP code returned for type UpdateConnectorUsingPUT1Forbidden
const UpdateConnectorUsingPUT1ForbiddenCode int = 403

/*UpdateConnectorUsingPUT1Forbidden Forbidden

swagger:response updateConnectorUsingPUT1Forbidden
*/
type UpdateConnectorUsingPUT1Forbidden struct {
}

// NewUpdateConnectorUsingPUT1Forbidden creates UpdateConnectorUsingPUT1Forbidden with default headers values
func NewUpdateConnectorUsingPUT1Forbidden() *UpdateConnectorUsingPUT1Forbidden {

	return &UpdateConnectorUsingPUT1Forbidden{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UpdateConnectorUsingPUT1NotFoundCode is the HTTP code returned for type UpdateConnectorUsingPUT1NotFound
const UpdateConnectorUsingPUT1NotFoundCode int = 404

/*UpdateConnectorUsingPUT1NotFound Not Found

swagger:response updateConnectorUsingPUT1NotFound
*/
type UpdateConnectorUsingPUT1NotFound struct {
}

// NewUpdateConnectorUsingPUT1NotFound creates UpdateConnectorUsingPUT1NotFound with default headers values
func NewUpdateConnectorUsingPUT1NotFound() *UpdateConnectorUsingPUT1NotFound {

	return &UpdateConnectorUsingPUT1NotFound{}
}

// WriteResponse to the client
func (o *UpdateConnectorUsingPUT1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
