/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package a_w_s_connector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateConnectorUsingPUT1HandlerFunc turns a function with the right signature into a update connector using p u t 1 handler
type UpdateConnectorUsingPUT1HandlerFunc func(UpdateConnectorUsingPUT1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConnectorUsingPUT1HandlerFunc) Handle(params UpdateConnectorUsingPUT1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateConnectorUsingPUT1Handler interface for that can handle valid update connector using p u t 1 params
type UpdateConnectorUsingPUT1Handler interface {
	Handle(UpdateConnectorUsingPUT1Params, interface{}) middleware.Responder
}

// NewUpdateConnectorUsingPUT1 creates a new http.Handler for the update connector using p u t 1 operation
func NewUpdateConnectorUsingPUT1(ctx *middleware.Context, handler UpdateConnectorUsingPUT1Handler) *UpdateConnectorUsingPUT1 {
	return &UpdateConnectorUsingPUT1{Context: ctx, Handler: handler}
}

/*UpdateConnectorUsingPUT1 swagger:route PUT /rest/v1/aws/connectors/{connectorId} AWS Connector updateConnectorUsingPUT1

Update the existing connector

*/
type UpdateConnectorUsingPUT1 struct {
	Context *middleware.Context
	Handler UpdateConnectorUsingPUT1Handler
}

func (o *UpdateConnectorUsingPUT1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateConnectorUsingPUT1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
