/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// CreatePagerActionUsingPOSTOKCode is the HTTP code returned for type CreatePagerActionUsingPOSTOK
const CreatePagerActionUsingPOSTOKCode int = 200

/*CreatePagerActionUsingPOSTOK OK

swagger:response createPagerActionUsingPOSTOK
*/
type CreatePagerActionUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseEntity `json:"body,omitempty"`
}

// NewCreatePagerActionUsingPOSTOK creates CreatePagerActionUsingPOSTOK with default headers values
func NewCreatePagerActionUsingPOSTOK() *CreatePagerActionUsingPOSTOK {

	return &CreatePagerActionUsingPOSTOK{}
}

// WithPayload adds the payload to the create pager action using p o s t o k response
func (o *CreatePagerActionUsingPOSTOK) WithPayload(payload *models.ResponseEntity) *CreatePagerActionUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pager action using p o s t o k response
func (o *CreatePagerActionUsingPOSTOK) SetPayload(payload *models.ResponseEntity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePagerActionUsingPOSTCreatedCode is the HTTP code returned for type CreatePagerActionUsingPOSTCreated
const CreatePagerActionUsingPOSTCreatedCode int = 201

/*CreatePagerActionUsingPOSTCreated Created

swagger:response createPagerActionUsingPOSTCreated
*/
type CreatePagerActionUsingPOSTCreated struct {
}

// NewCreatePagerActionUsingPOSTCreated creates CreatePagerActionUsingPOSTCreated with default headers values
func NewCreatePagerActionUsingPOSTCreated() *CreatePagerActionUsingPOSTCreated {

	return &CreatePagerActionUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreatePagerActionUsingPOSTBadRequestCode is the HTTP code returned for type CreatePagerActionUsingPOSTBadRequest
const CreatePagerActionUsingPOSTBadRequestCode int = 400

/*CreatePagerActionUsingPOSTBadRequest Bad Request

swagger:response createPagerActionUsingPOSTBadRequest
*/
type CreatePagerActionUsingPOSTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewCreatePagerActionUsingPOSTBadRequest creates CreatePagerActionUsingPOSTBadRequest with default headers values
func NewCreatePagerActionUsingPOSTBadRequest() *CreatePagerActionUsingPOSTBadRequest {

	return &CreatePagerActionUsingPOSTBadRequest{}
}

// WithPayload adds the payload to the create pager action using p o s t bad request response
func (o *CreatePagerActionUsingPOSTBadRequest) WithPayload(payload *models.APIErrorFacade) *CreatePagerActionUsingPOSTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pager action using p o s t bad request response
func (o *CreatePagerActionUsingPOSTBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePagerActionUsingPOSTUnauthorizedCode is the HTTP code returned for type CreatePagerActionUsingPOSTUnauthorized
const CreatePagerActionUsingPOSTUnauthorizedCode int = 401

/*CreatePagerActionUsingPOSTUnauthorized Unauthorized user

swagger:response createPagerActionUsingPOSTUnauthorized
*/
type CreatePagerActionUsingPOSTUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewCreatePagerActionUsingPOSTUnauthorized creates CreatePagerActionUsingPOSTUnauthorized with default headers values
func NewCreatePagerActionUsingPOSTUnauthorized() *CreatePagerActionUsingPOSTUnauthorized {

	return &CreatePagerActionUsingPOSTUnauthorized{}
}

// WithPayload adds the payload to the create pager action using p o s t unauthorized response
func (o *CreatePagerActionUsingPOSTUnauthorized) WithPayload(payload *models.APIErrorFacade) *CreatePagerActionUsingPOSTUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pager action using p o s t unauthorized response
func (o *CreatePagerActionUsingPOSTUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePagerActionUsingPOSTForbiddenCode is the HTTP code returned for type CreatePagerActionUsingPOSTForbidden
const CreatePagerActionUsingPOSTForbiddenCode int = 403

/*CreatePagerActionUsingPOSTForbidden Forbidden

swagger:response createPagerActionUsingPOSTForbidden
*/
type CreatePagerActionUsingPOSTForbidden struct {
}

// NewCreatePagerActionUsingPOSTForbidden creates CreatePagerActionUsingPOSTForbidden with default headers values
func NewCreatePagerActionUsingPOSTForbidden() *CreatePagerActionUsingPOSTForbidden {

	return &CreatePagerActionUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreatePagerActionUsingPOSTNotFoundCode is the HTTP code returned for type CreatePagerActionUsingPOSTNotFound
const CreatePagerActionUsingPOSTNotFoundCode int = 404

/*CreatePagerActionUsingPOSTNotFound Not Found

swagger:response createPagerActionUsingPOSTNotFound
*/
type CreatePagerActionUsingPOSTNotFound struct {
}

// NewCreatePagerActionUsingPOSTNotFound creates CreatePagerActionUsingPOSTNotFound with default headers values
func NewCreatePagerActionUsingPOSTNotFound() *CreatePagerActionUsingPOSTNotFound {

	return &CreatePagerActionUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *CreatePagerActionUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
