/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreatePagerActionUsingPOSTHandlerFunc turns a function with the right signature into a create pager action using p o s t handler
type CreatePagerActionUsingPOSTHandlerFunc func(CreatePagerActionUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePagerActionUsingPOSTHandlerFunc) Handle(params CreatePagerActionUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreatePagerActionUsingPOSTHandler interface for that can handle valid create pager action using p o s t params
type CreatePagerActionUsingPOSTHandler interface {
	Handle(CreatePagerActionUsingPOSTParams, interface{}) middleware.Responder
}

// NewCreatePagerActionUsingPOST creates a new http.Handler for the create pager action using p o s t operation
func NewCreatePagerActionUsingPOST(ctx *middleware.Context, handler CreatePagerActionUsingPOSTHandler) *CreatePagerActionUsingPOST {
	return &CreatePagerActionUsingPOST{Context: ctx, Handler: handler}
}

/*CreatePagerActionUsingPOST swagger:route POST /rest/v1/actions/pagerduty Response Actions createPagerActionUsingPOST

Create a new pagerDuty action

*/
type CreatePagerActionUsingPOST struct {
	Context *middleware.Context
	Handler CreatePagerActionUsingPOSTHandler
}

func (o *CreatePagerActionUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatePagerActionUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
