/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateSlackActionUsingPOSTHandlerFunc turns a function with the right signature into a create slack action using p o s t handler
type CreateSlackActionUsingPOSTHandlerFunc func(CreateSlackActionUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateSlackActionUsingPOSTHandlerFunc) Handle(params CreateSlackActionUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateSlackActionUsingPOSTHandler interface for that can handle valid create slack action using p o s t params
type CreateSlackActionUsingPOSTHandler interface {
	Handle(CreateSlackActionUsingPOSTParams, interface{}) middleware.Responder
}

// NewCreateSlackActionUsingPOST creates a new http.Handler for the create slack action using p o s t operation
func NewCreateSlackActionUsingPOST(ctx *middleware.Context, handler CreateSlackActionUsingPOSTHandler) *CreateSlackActionUsingPOST {
	return &CreateSlackActionUsingPOST{Context: ctx, Handler: handler}
}

/*CreateSlackActionUsingPOST swagger:route POST /rest/v1/actions/slack Response Actions createSlackActionUsingPOST

Create a new Slack action

*/
type CreateSlackActionUsingPOST struct {
	Context *middleware.Context
	Handler CreateSlackActionUsingPOSTHandler
}

func (o *CreateSlackActionUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateSlackActionUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
