/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// TestSlackActionUsingPOST1OKCode is the HTTP code returned for type TestSlackActionUsingPOST1OK
const TestSlackActionUsingPOST1OKCode int = 200

/*TestSlackActionUsingPOST1OK OK

swagger:response testSlackActionUsingPOST1OK
*/
type TestSlackActionUsingPOST1OK struct {

	/*
	  In: Body
	*/
	Payload *models.SlackConnectionParam `json:"body,omitempty"`
}

// NewTestSlackActionUsingPOST1OK creates TestSlackActionUsingPOST1OK with default headers values
func NewTestSlackActionUsingPOST1OK() *TestSlackActionUsingPOST1OK {

	return &TestSlackActionUsingPOST1OK{}
}

// WithPayload adds the payload to the test slack action using p o s t1 o k response
func (o *TestSlackActionUsingPOST1OK) WithPayload(payload *models.SlackConnectionParam) *TestSlackActionUsingPOST1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the test slack action using p o s t1 o k response
func (o *TestSlackActionUsingPOST1OK) SetPayload(payload *models.SlackConnectionParam) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TestSlackActionUsingPOST1CreatedCode is the HTTP code returned for type TestSlackActionUsingPOST1Created
const TestSlackActionUsingPOST1CreatedCode int = 201

/*TestSlackActionUsingPOST1Created Created

swagger:response testSlackActionUsingPOST1Created
*/
type TestSlackActionUsingPOST1Created struct {
}

// NewTestSlackActionUsingPOST1Created creates TestSlackActionUsingPOST1Created with default headers values
func NewTestSlackActionUsingPOST1Created() *TestSlackActionUsingPOST1Created {

	return &TestSlackActionUsingPOST1Created{}
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// TestSlackActionUsingPOST1BadRequestCode is the HTTP code returned for type TestSlackActionUsingPOST1BadRequest
const TestSlackActionUsingPOST1BadRequestCode int = 400

/*TestSlackActionUsingPOST1BadRequest Bad Request

swagger:response testSlackActionUsingPOST1BadRequest
*/
type TestSlackActionUsingPOST1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewTestSlackActionUsingPOST1BadRequest creates TestSlackActionUsingPOST1BadRequest with default headers values
func NewTestSlackActionUsingPOST1BadRequest() *TestSlackActionUsingPOST1BadRequest {

	return &TestSlackActionUsingPOST1BadRequest{}
}

// WithPayload adds the payload to the test slack action using p o s t1 bad request response
func (o *TestSlackActionUsingPOST1BadRequest) WithPayload(payload *models.APIErrorFacade) *TestSlackActionUsingPOST1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the test slack action using p o s t1 bad request response
func (o *TestSlackActionUsingPOST1BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TestSlackActionUsingPOST1UnauthorizedCode is the HTTP code returned for type TestSlackActionUsingPOST1Unauthorized
const TestSlackActionUsingPOST1UnauthorizedCode int = 401

/*TestSlackActionUsingPOST1Unauthorized Unauthorized user

swagger:response testSlackActionUsingPOST1Unauthorized
*/
type TestSlackActionUsingPOST1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewTestSlackActionUsingPOST1Unauthorized creates TestSlackActionUsingPOST1Unauthorized with default headers values
func NewTestSlackActionUsingPOST1Unauthorized() *TestSlackActionUsingPOST1Unauthorized {

	return &TestSlackActionUsingPOST1Unauthorized{}
}

// WithPayload adds the payload to the test slack action using p o s t1 unauthorized response
func (o *TestSlackActionUsingPOST1Unauthorized) WithPayload(payload *models.APIErrorFacade) *TestSlackActionUsingPOST1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the test slack action using p o s t1 unauthorized response
func (o *TestSlackActionUsingPOST1Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TestSlackActionUsingPOST1ForbiddenCode is the HTTP code returned for type TestSlackActionUsingPOST1Forbidden
const TestSlackActionUsingPOST1ForbiddenCode int = 403

/*TestSlackActionUsingPOST1Forbidden Forbidden

swagger:response testSlackActionUsingPOST1Forbidden
*/
type TestSlackActionUsingPOST1Forbidden struct {
}

// NewTestSlackActionUsingPOST1Forbidden creates TestSlackActionUsingPOST1Forbidden with default headers values
func NewTestSlackActionUsingPOST1Forbidden() *TestSlackActionUsingPOST1Forbidden {

	return &TestSlackActionUsingPOST1Forbidden{}
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// TestSlackActionUsingPOST1NotFoundCode is the HTTP code returned for type TestSlackActionUsingPOST1NotFound
const TestSlackActionUsingPOST1NotFoundCode int = 404

/*TestSlackActionUsingPOST1NotFound Not Found

swagger:response testSlackActionUsingPOST1NotFound
*/
type TestSlackActionUsingPOST1NotFound struct {
}

// NewTestSlackActionUsingPOST1NotFound creates TestSlackActionUsingPOST1NotFound with default headers values
func NewTestSlackActionUsingPOST1NotFound() *TestSlackActionUsingPOST1NotFound {

	return &TestSlackActionUsingPOST1NotFound{}
}

// WriteResponse to the client
func (o *TestSlackActionUsingPOST1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
