/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// TestSlackActionUsingPOSTHandlerFunc turns a function with the right signature into a test slack action using p o s t handler
type TestSlackActionUsingPOSTHandlerFunc func(TestSlackActionUsingPOSTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn TestSlackActionUsingPOSTHandlerFunc) Handle(params TestSlackActionUsingPOSTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// TestSlackActionUsingPOSTHandler interface for that can handle valid test slack action using p o s t params
type TestSlackActionUsingPOSTHandler interface {
	Handle(TestSlackActionUsingPOSTParams, interface{}) middleware.Responder
}

// NewTestSlackActionUsingPOST creates a new http.Handler for the test slack action using p o s t operation
func NewTestSlackActionUsingPOST(ctx *middleware.Context, handler TestSlackActionUsingPOSTHandler) *TestSlackActionUsingPOST {
	return &TestSlackActionUsingPOST{Context: ctx, Handler: handler}
}

/*TestSlackActionUsingPOST swagger:route POST /rest/v1/actions/pagerduty/test Response Actions testSlackActionUsingPOST

Test pagerDuty action

*/
type TestSlackActionUsingPOST struct {
	Context *middleware.Context
	Handler TestSlackActionUsingPOSTHandler
}

func (o *TestSlackActionUsingPOST) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTestSlackActionUsingPOSTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
