/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdatePagerActionUsingPUTHandlerFunc turns a function with the right signature into a update pager action using p u t handler
type UpdatePagerActionUsingPUTHandlerFunc func(UpdatePagerActionUsingPUTParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePagerActionUsingPUTHandlerFunc) Handle(params UpdatePagerActionUsingPUTParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdatePagerActionUsingPUTHandler interface for that can handle valid update pager action using p u t params
type UpdatePagerActionUsingPUTHandler interface {
	Handle(UpdatePagerActionUsingPUTParams, interface{}) middleware.Responder
}

// NewUpdatePagerActionUsingPUT creates a new http.Handler for the update pager action using p u t operation
func NewUpdatePagerActionUsingPUT(ctx *middleware.Context, handler UpdatePagerActionUsingPUTHandler) *UpdatePagerActionUsingPUT {
	return &UpdatePagerActionUsingPUT{Context: ctx, Handler: handler}
}

/*UpdatePagerActionUsingPUT swagger:route PUT /rest/v1/actions/pagerduty/{pagerActionId} Response Actions updatePagerActionUsingPUT

Update pagerDuty action

*/
type UpdatePagerActionUsingPUT struct {
	Context *middleware.Context
	Handler UpdatePagerActionUsingPUTHandler
}

func (o *UpdatePagerActionUsingPUT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdatePagerActionUsingPUTParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
