/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// UpdateSlackActionUsingPUTOKCode is the HTTP code returned for type UpdateSlackActionUsingPUTOK
const UpdateSlackActionUsingPUTOKCode int = 200

/*UpdateSlackActionUsingPUTOK OK

swagger:response updateSlackActionUsingPUTOK
*/
type UpdateSlackActionUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseEntity `json:"body,omitempty"`
}

// NewUpdateSlackActionUsingPUTOK creates UpdateSlackActionUsingPUTOK with default headers values
func NewUpdateSlackActionUsingPUTOK() *UpdateSlackActionUsingPUTOK {

	return &UpdateSlackActionUsingPUTOK{}
}

// WithPayload adds the payload to the update slack action using p u t o k response
func (o *UpdateSlackActionUsingPUTOK) WithPayload(payload *models.ResponseEntity) *UpdateSlackActionUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update slack action using p u t o k response
func (o *UpdateSlackActionUsingPUTOK) SetPayload(payload *models.ResponseEntity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSlackActionUsingPUTCreatedCode is the HTTP code returned for type UpdateSlackActionUsingPUTCreated
const UpdateSlackActionUsingPUTCreatedCode int = 201

/*UpdateSlackActionUsingPUTCreated Created

swagger:response updateSlackActionUsingPUTCreated
*/
type UpdateSlackActionUsingPUTCreated struct {
}

// NewUpdateSlackActionUsingPUTCreated creates UpdateSlackActionUsingPUTCreated with default headers values
func NewUpdateSlackActionUsingPUTCreated() *UpdateSlackActionUsingPUTCreated {

	return &UpdateSlackActionUsingPUTCreated{}
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// UpdateSlackActionUsingPUTBadRequestCode is the HTTP code returned for type UpdateSlackActionUsingPUTBadRequest
const UpdateSlackActionUsingPUTBadRequestCode int = 400

/*UpdateSlackActionUsingPUTBadRequest Bad Request

swagger:response updateSlackActionUsingPUTBadRequest
*/
type UpdateSlackActionUsingPUTBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateSlackActionUsingPUTBadRequest creates UpdateSlackActionUsingPUTBadRequest with default headers values
func NewUpdateSlackActionUsingPUTBadRequest() *UpdateSlackActionUsingPUTBadRequest {

	return &UpdateSlackActionUsingPUTBadRequest{}
}

// WithPayload adds the payload to the update slack action using p u t bad request response
func (o *UpdateSlackActionUsingPUTBadRequest) WithPayload(payload *models.APIErrorFacade) *UpdateSlackActionUsingPUTBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update slack action using p u t bad request response
func (o *UpdateSlackActionUsingPUTBadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSlackActionUsingPUTUnauthorizedCode is the HTTP code returned for type UpdateSlackActionUsingPUTUnauthorized
const UpdateSlackActionUsingPUTUnauthorizedCode int = 401

/*UpdateSlackActionUsingPUTUnauthorized Unauthorized user

swagger:response updateSlackActionUsingPUTUnauthorized
*/
type UpdateSlackActionUsingPUTUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewUpdateSlackActionUsingPUTUnauthorized creates UpdateSlackActionUsingPUTUnauthorized with default headers values
func NewUpdateSlackActionUsingPUTUnauthorized() *UpdateSlackActionUsingPUTUnauthorized {

	return &UpdateSlackActionUsingPUTUnauthorized{}
}

// WithPayload adds the payload to the update slack action using p u t unauthorized response
func (o *UpdateSlackActionUsingPUTUnauthorized) WithPayload(payload *models.APIErrorFacade) *UpdateSlackActionUsingPUTUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update slack action using p u t unauthorized response
func (o *UpdateSlackActionUsingPUTUnauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSlackActionUsingPUTForbiddenCode is the HTTP code returned for type UpdateSlackActionUsingPUTForbidden
const UpdateSlackActionUsingPUTForbiddenCode int = 403

/*UpdateSlackActionUsingPUTForbidden Forbidden

swagger:response updateSlackActionUsingPUTForbidden
*/
type UpdateSlackActionUsingPUTForbidden struct {
}

// NewUpdateSlackActionUsingPUTForbidden creates UpdateSlackActionUsingPUTForbidden with default headers values
func NewUpdateSlackActionUsingPUTForbidden() *UpdateSlackActionUsingPUTForbidden {

	return &UpdateSlackActionUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UpdateSlackActionUsingPUTNotFoundCode is the HTTP code returned for type UpdateSlackActionUsingPUTNotFound
const UpdateSlackActionUsingPUTNotFoundCode int = 404

/*UpdateSlackActionUsingPUTNotFound Not Found

swagger:response updateSlackActionUsingPUTNotFound
*/
type UpdateSlackActionUsingPUTNotFound struct {
}

// NewUpdateSlackActionUsingPUTNotFound creates UpdateSlackActionUsingPUTNotFound with default headers values
func NewUpdateSlackActionUsingPUTNotFound() *UpdateSlackActionUsingPUTNotFound {

	return &UpdateSlackActionUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *UpdateSlackActionUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
