/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// NewUpdatePagerActionUsingPUTParams creates a new UpdatePagerActionUsingPUTParams object
// no default values defined in spec.
func NewUpdatePagerActionUsingPUTParams() UpdatePagerActionUsingPUTParams {

	return UpdatePagerActionUsingPUTParams{}
}

// UpdatePagerActionUsingPUTParams contains all the bound params for the update pager action using p u t operation
// typically these are obtained from a http.Request
//
// swagger:parameters updatePagerActionUsingPUT
type UpdatePagerActionUsingPUTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the pagerAction ID of a specific action in the user’s scope.
	  Required: true
	  In: path
	*/
	PagerActionID string
	/*pagerdutyUpdateRequest
	  Required: true
	  In: body
	*/
	PagerdutyUpdateRequest *models.PagerdutyUpdateRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdatePagerActionUsingPUTParams() beforehand.
func (o *UpdatePagerActionUsingPUTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPagerActionID, rhkPagerActionID, _ := route.Params.GetOK("pagerActionId")
	if err := o.bindPagerActionID(rPagerActionID, rhkPagerActionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PagerdutyUpdateRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("pagerdutyUpdateRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("pagerdutyUpdateRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.PagerdutyUpdateRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("pagerdutyUpdateRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPagerActionID binds and validates parameter PagerActionID from path.
func (o *UpdatePagerActionUsingPUTParams) bindPagerActionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.PagerActionID = raw

	return nil
}
