/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package response_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// NewUpdateEmailActionUsingPUTParams creates a new UpdateEmailActionUsingPUTParams object
// no default values defined in spec.
func NewUpdateEmailActionUsingPUTParams() UpdateEmailActionUsingPUTParams {

	return UpdateEmailActionUsingPUTParams{}
}

// UpdateEmailActionUsingPUTParams contains all the bound params for the update email action using p u t operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateEmailActionUsingPUT
type UpdateEmailActionUsingPUTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Specify the Email ID of a specific action in the user’s scope.
	  Required: true
	  In: path
	*/
	EmailActionID string
	/*emailActionUpdateRequest
	  Required: true
	  In: body
	*/
	EmailActionUpdateRequest *models.EmailActionUpdateRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateEmailActionUsingPUTParams() beforehand.
func (o *UpdateEmailActionUsingPUTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rEmailActionID, rhkEmailActionID, _ := route.Params.GetOK("emailActionId")
	if err := o.bindEmailActionID(rEmailActionID, rhkEmailActionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.EmailActionUpdateRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("emailActionUpdateRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("emailActionUpdateRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.EmailActionUpdateRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("emailActionUpdateRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmailActionID binds and validates parameter EmailActionID from path.
func (o *UpdateEmailActionUsingPUTParams) bindEmailActionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.EmailActionID = raw

	return nil
}
