/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEvaluationsStatsUsingGET1Params creates a new GetEvaluationsStatsUsingGET1Params object
// no default values defined in spec.
func NewGetEvaluationsStatsUsingGET1Params() GetEvaluationsStatsUsingGET1Params {

	return GetEvaluationsStatsUsingGET1Params{}
}

// GetEvaluationsStatsUsingGET1Params contains all the bound params for the get evaluations stats using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters getEvaluationsStatsUsingGET_1
type GetEvaluationsStatsUsingGET1Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*connectorId
	  Required: true
	  In: path
	*/
	ConnectorID string
	/*controlId
	  Required: true
	  In: path
	*/
	ControlID string
	/*resourceId
	  Required: true
	  In: query
	*/
	ResourceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEvaluationsStatsUsingGET1Params() beforehand.
func (o *GetEvaluationsStatsUsingGET1Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rConnectorID, rhkConnectorID, _ := route.Params.GetOK("connectorId")
	if err := o.bindConnectorID(rConnectorID, rhkConnectorID, route.Formats); err != nil {
		res = append(res, err)
	}

	rControlID, rhkControlID, _ := route.Params.GetOK("controlId")
	if err := o.bindControlID(rControlID, rhkControlID, route.Formats); err != nil {
		res = append(res, err)
	}

	qResourceID, qhkResourceID, _ := qs.GetOK("resourceId")
	if err := o.bindResourceID(qResourceID, qhkResourceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindConnectorID binds and validates parameter ConnectorID from path.
func (o *GetEvaluationsStatsUsingGET1Params) bindConnectorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ConnectorID = raw

	return nil
}

// bindControlID binds and validates parameter ControlID from path.
func (o *GetEvaluationsStatsUsingGET1Params) bindControlID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ControlID = raw

	return nil
}

// bindResourceID binds and validates parameter ResourceID from query.
func (o *GetEvaluationsStatsUsingGET1Params) bindResourceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("resourceId", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("resourceId", "query", raw); err != nil {
		return err
	}

	o.ResourceID = raw

	return nil
}
