/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// GetEvaluatedResourcesUsingGET1OKCode is the HTTP code returned for type GetEvaluatedResourcesUsingGET1OK
const GetEvaluatedResourcesUsingGET1OKCode int = 200

/*GetEvaluatedResourcesUsingGET1OK OK

swagger:response getEvaluatedResourcesUsingGET1OK
*/
type GetEvaluatedResourcesUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.PageImplAzureEvaluationDetailResponse `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGET1OK creates GetEvaluatedResourcesUsingGET1OK with default headers values
func NewGetEvaluatedResourcesUsingGET1OK() *GetEvaluatedResourcesUsingGET1OK {

	return &GetEvaluatedResourcesUsingGET1OK{}
}

// WithPayload adds the payload to the get evaluated resources using g e t1 o k response
func (o *GetEvaluatedResourcesUsingGET1OK) WithPayload(payload *models.PageImplAzureEvaluationDetailResponse) *GetEvaluatedResourcesUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t1 o k response
func (o *GetEvaluatedResourcesUsingGET1OK) SetPayload(payload *models.PageImplAzureEvaluationDetailResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGET1BadRequestCode is the HTTP code returned for type GetEvaluatedResourcesUsingGET1BadRequest
const GetEvaluatedResourcesUsingGET1BadRequestCode int = 400

/*GetEvaluatedResourcesUsingGET1BadRequest Bad Request

swagger:response getEvaluatedResourcesUsingGET1BadRequest
*/
type GetEvaluatedResourcesUsingGET1BadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGET1BadRequest creates GetEvaluatedResourcesUsingGET1BadRequest with default headers values
func NewGetEvaluatedResourcesUsingGET1BadRequest() *GetEvaluatedResourcesUsingGET1BadRequest {

	return &GetEvaluatedResourcesUsingGET1BadRequest{}
}

// WithPayload adds the payload to the get evaluated resources using g e t1 bad request response
func (o *GetEvaluatedResourcesUsingGET1BadRequest) WithPayload(payload *models.APIErrorFacade) *GetEvaluatedResourcesUsingGET1BadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t1 bad request response
func (o *GetEvaluatedResourcesUsingGET1BadRequest) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGET1BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGET1UnauthorizedCode is the HTTP code returned for type GetEvaluatedResourcesUsingGET1Unauthorized
const GetEvaluatedResourcesUsingGET1UnauthorizedCode int = 401

/*GetEvaluatedResourcesUsingGET1Unauthorized Unauthorized user

swagger:response getEvaluatedResourcesUsingGET1Unauthorized
*/
type GetEvaluatedResourcesUsingGET1Unauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorFacade `json:"body,omitempty"`
}

// NewGetEvaluatedResourcesUsingGET1Unauthorized creates GetEvaluatedResourcesUsingGET1Unauthorized with default headers values
func NewGetEvaluatedResourcesUsingGET1Unauthorized() *GetEvaluatedResourcesUsingGET1Unauthorized {

	return &GetEvaluatedResourcesUsingGET1Unauthorized{}
}

// WithPayload adds the payload to the get evaluated resources using g e t1 unauthorized response
func (o *GetEvaluatedResourcesUsingGET1Unauthorized) WithPayload(payload *models.APIErrorFacade) *GetEvaluatedResourcesUsingGET1Unauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get evaluated resources using g e t1 unauthorized response
func (o *GetEvaluatedResourcesUsingGET1Unauthorized) SetPayload(payload *models.APIErrorFacade) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEvaluatedResourcesUsingGET1ForbiddenCode is the HTTP code returned for type GetEvaluatedResourcesUsingGET1Forbidden
const GetEvaluatedResourcesUsingGET1ForbiddenCode int = 403

/*GetEvaluatedResourcesUsingGET1Forbidden Forbidden

swagger:response getEvaluatedResourcesUsingGET1Forbidden
*/
type GetEvaluatedResourcesUsingGET1Forbidden struct {
}

// NewGetEvaluatedResourcesUsingGET1Forbidden creates GetEvaluatedResourcesUsingGET1Forbidden with default headers values
func NewGetEvaluatedResourcesUsingGET1Forbidden() *GetEvaluatedResourcesUsingGET1Forbidden {

	return &GetEvaluatedResourcesUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetEvaluatedResourcesUsingGET1NotFoundCode is the HTTP code returned for type GetEvaluatedResourcesUsingGET1NotFound
const GetEvaluatedResourcesUsingGET1NotFoundCode int = 404

/*GetEvaluatedResourcesUsingGET1NotFound Not Found

swagger:response getEvaluatedResourcesUsingGET1NotFound
*/
type GetEvaluatedResourcesUsingGET1NotFound struct {
}

// NewGetEvaluatedResourcesUsingGET1NotFound creates GetEvaluatedResourcesUsingGET1NotFound with default headers values
func NewGetEvaluatedResourcesUsingGET1NotFound() *GetEvaluatedResourcesUsingGET1NotFound {

	return &GetEvaluatedResourcesUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *GetEvaluatedResourcesUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
