/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package azure_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEvaluationsStatsUsingGET1HandlerFunc turns a function with the right signature into a get evaluations stats using g e t 1 handler
type GetEvaluationsStatsUsingGET1HandlerFunc func(GetEvaluationsStatsUsingGET1Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEvaluationsStatsUsingGET1HandlerFunc) Handle(params GetEvaluationsStatsUsingGET1Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetEvaluationsStatsUsingGET1Handler interface for that can handle valid get evaluations stats using g e t 1 params
type GetEvaluationsStatsUsingGET1Handler interface {
	Handle(GetEvaluationsStatsUsingGET1Params, interface{}) middleware.Responder
}

// NewGetEvaluationsStatsUsingGET1 creates a new http.Handler for the get evaluations stats using g e t 1 operation
func NewGetEvaluationsStatsUsingGET1(ctx *middleware.Context, handler GetEvaluationsStatsUsingGET1Handler) *GetEvaluationsStatsUsingGET1 {
	return &GetEvaluationsStatsUsingGET1{Context: ctx, Handler: handler}
}

/*GetEvaluationsStatsUsingGET1 swagger:route GET /rest/v1/azure/evaluations/stats/{controlId}/{connectorId} Azure Evaluations getEvaluationsStatsUsingGET1

Get the stats for specified control id and resource id

*/
type GetEvaluationsStatsUsingGET1 struct {
	Context *middleware.Context
	Handler GetEvaluationsStatsUsingGET1Handler
}

func (o *GetEvaluationsStatsUsingGET1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEvaluationsStatsUsingGET1Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
