/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package g_c_p_evaluations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEvaluatedResourcesUsingGET2HandlerFunc turns a function with the right signature into a get evaluated resources using g e t 2 handler
type GetEvaluatedResourcesUsingGET2HandlerFunc func(GetEvaluatedResourcesUsingGET2Params, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEvaluatedResourcesUsingGET2HandlerFunc) Handle(params GetEvaluatedResourcesUsingGET2Params, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetEvaluatedResourcesUsingGET2Handler interface for that can handle valid get evaluated resources using g e t 2 params
type GetEvaluatedResourcesUsingGET2Handler interface {
	Handle(GetEvaluatedResourcesUsingGET2Params, interface{}) middleware.Responder
}

// NewGetEvaluatedResourcesUsingGET2 creates a new http.Handler for the get evaluated resources using g e t 2 operation
func NewGetEvaluatedResourcesUsingGET2(ctx *middleware.Context, handler GetEvaluatedResourcesUsingGET2Handler) *GetEvaluatedResourcesUsingGET2 {
	return &GetEvaluatedResourcesUsingGET2{Context: ctx, Handler: handler}
}

/*GetEvaluatedResourcesUsingGET2 swagger:route GET /rest/v1/gcp/evaluations/{projectId}/resources/{controlId} GCP Evaluations getEvaluatedResourcesUsingGET2

Get the resources evaluated for the specified GCP account and control id

*/
type GetEvaluatedResourcesUsingGET2 struct {
	Context *middleware.Context
	Handler GetEvaluatedResourcesUsingGET2Handler
}

func (o *GetEvaluatedResourcesUsingGET2) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEvaluatedResourcesUsingGET2Params()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
