/* #nosec */ // Code generated by go-swagger; DO NOT EDIT.

package connector_groups_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/form3tech-oss/terraform-provider-qualys/swagger/models"
)

// NewUpdateGroupUsingPOSTParams creates a new UpdateGroupUsingPOSTParams object
// no default values defined in spec.
func NewUpdateGroupUsingPOSTParams() UpdateGroupUsingPOSTParams {

	return UpdateGroupUsingPOSTParams{}
}

// UpdateGroupUsingPOSTParams contains all the bound params for the update group using p o s t operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateGroupUsingPOST
type UpdateGroupUsingPOSTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Cloud type
	  Required: true
	  In: query
	*/
	CloudType string
	/*Group Modify Request
	  Required: true
	  In: body
	*/
	ConnectorGroupModifyRequest *models.ConnectorGroupModifyRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateGroupUsingPOSTParams() beforehand.
func (o *UpdateGroupUsingPOSTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCloudType, qhkCloudType, _ := qs.GetOK("cloudType")
	if err := o.bindCloudType(qCloudType, qhkCloudType, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ConnectorGroupModifyRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("connectorGroupModifyRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("connectorGroupModifyRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ConnectorGroupModifyRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("connectorGroupModifyRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCloudType binds and validates parameter CloudType from query.
func (o *UpdateGroupUsingPOSTParams) bindCloudType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("cloudType", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("cloudType", "query", raw); err != nil {
		return err
	}

	o.CloudType = raw

	if err := o.validateCloudType(formats); err != nil {
		return err
	}

	return nil
}

// validateCloudType carries on validations for parameter CloudType
func (o *UpdateGroupUsingPOSTParams) validateCloudType(formats strfmt.Registry) error {

	if err := validate.EnumCase("cloudType", "query", o.CloudType, []interface{}{"AWS", "AZURE", "GCP"}, true); err != nil {
		return err
	}

	return nil
}
